-- ============================================================
-- DATABASE CHUẨN HÓA TIẾNG VIỆT - PHIÊN BẢN MỞ RỘNG
-- Import file này vào phpMyAdmin (XAMPP)
-- ============================================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- Tạo database
CREATE DATABASE IF NOT EXISTS `vietnamese_normalizer`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `vietnamese_normalizer`;

-- ============================================================
-- BẢNG 1: TỪ ĐIỂN TIẾNG VIỆT
-- ============================================================
DROP TABLE IF EXISTS `vietnamese_words`;
CREATE TABLE `vietnamese_words` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `word` VARCHAR(50) NOT NULL COMMENT 'Từ không dấu',
    `word_with_accent` VARCHAR(50) NOT NULL COMMENT 'Từ có dấu',
    `frequency` INT DEFAULT 1 COMMENT 'Tần suất sử dụng',
    `first_letter` CHAR(5) COMMENT 'Chữ cái đầu (index)',
    INDEX `idx_word` (`word`),
    INDEX `idx_first_letter` (`first_letter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- BẢNG 2: TỪ VIẾT TẮT / TEENCODE
-- ============================================================
DROP TABLE IF EXISTS `abbreviations`;
CREATE TABLE `abbreviations` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `abbreviation` VARCHAR(20) NOT NULL COMMENT 'Từ viết tắt',
    `full_word` VARCHAR(50) NOT NULL COMMENT 'Từ đầy đủ không dấu',
    `full_word_accent` VARCHAR(50) NOT NULL COMMENT 'Từ đầy đủ có dấu',
    `priority` INT DEFAULT 1 COMMENT 'Độ ưu tiên',
    INDEX `idx_abbr` (`abbreviation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- BẢNG 3: BIGRAMS (CẶP TỪ ĐI CÙNG NHAU)
-- ============================================================
DROP TABLE IF EXISTS `bigrams`;
CREATE TABLE `bigrams` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `word1` VARCHAR(50) NOT NULL COMMENT 'Từ thứ nhất',
    `word2` VARCHAR(50) NOT NULL COMMENT 'Từ thứ hai',
    `frequency` INT DEFAULT 1 COMMENT 'Tần suất xuất hiện',
    INDEX `idx_word1` (`word1`),
    INDEX `idx_bigram` (`word1`, `word2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- BẢNG 4: TỪ LÁY
-- ============================================================
DROP TABLE IF EXISTS `reduplicative_words`;
CREATE TABLE `reduplicative_words` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `word_no_accent` VARCHAR(50) NOT NULL COMMENT 'Từ láy không dấu',
    `word_with_accent` VARCHAR(50) NOT NULL COMMENT 'Từ láy có dấu',
    `type` VARCHAR(20) DEFAULT 'full' COMMENT 'Loại: full/initial/rhyme',
    `frequency` INT DEFAULT 1 COMMENT 'Tần suất',
    INDEX `idx_redup` (`word_no_accent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- BẢNG 5: TRIGRAMS (BỘ BA TỪ) - MỚI
-- ============================================================
DROP TABLE IF EXISTS `trigrams`;
CREATE TABLE `trigrams` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `word1` VARCHAR(50) NOT NULL,
    `word2` VARCHAR(50) NOT NULL,
    `word3` VARCHAR(50) NOT NULL,
    `frequency` INT DEFAULT 1,
    INDEX `idx_tri_w1` (`word1`),
    INDEX `idx_tri_w1w2` (`word1`, `word2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- BẢNG 6: MẪU LỖI CHÍNH TẢ PHỔ BIẾN - MỚI
-- ============================================================
DROP TABLE IF EXISTS `common_misspellings`;
CREATE TABLE `common_misspellings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `misspelling` VARCHAR(50) NOT NULL COMMENT 'Từ sai chính tả',
    `correct_word` VARCHAR(50) NOT NULL COMMENT 'Từ đúng không dấu',
    `correct_accent` VARCHAR(50) NOT NULL COMMENT 'Từ đúng có dấu',
    `error_type` VARCHAR(30) DEFAULT 'typo' COMMENT 'Loại lỗi: typo/phonetic/keyboard',
    INDEX `idx_misspell` (`misspelling`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ############################################################
--                    SEED DỮ LIỆU
-- ############################################################

-- ============================================================
-- 1. VIETNAMESE_WORDS (~1500+ từ)
-- ============================================================

INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
-- ĐẠI TỪ NHÂN XƯNG (35+)
('toi', 'tôi', 100, 't'),
('minh', 'mình', 95, 'm'),
('ban', 'bạn', 95, 'b'),
('anh', 'anh', 95, 'a'),
('em', 'em', 95, 'e'),
('chi', 'chị', 90, 'c'),
('no', 'nó', 85, 'n'),
('ho', 'họ', 80, 'h'),
('chung', 'chúng', 75, 'c'),
('ta', 'ta', 80, 't'),
('cau', 'cậu', 75, 'c'),
('may', 'mày', 60, 'm'),
('tao', 'tao', 60, 't'),
('ong', 'ông', 80, 'o'),
('ba', 'bà', 80, 'b'),
('co', 'cô', 80, 'c'),
('chu', 'chú', 75, 'c'),
('con', 'con', 85, 'c'),
('me', 'mẹ', 85, 'm'),
('bo', 'bố', 85, 'b'),
('cha', 'cha', 80, 'c'),
('chau', 'cháu', 70, 'c'),
('di', 'dì', 65, 'd'),
('duong', 'dượng', 55, 'd'),
('thim', 'thím', 55, 't'),
('moi nguoi', 'mọi người', 70, 'm'),
('ai', 'ai', 75, 'a'),
('tui', 'tui', 70, 't'),
('nguoi', 'người', 85, 'n'),
('nguoi ta', 'người ta', 70, 'n'),
('cac ban', 'các bạn', 65, 'c'),
('chung toi', 'chúng tôi', 65, 'c'),
('chung ta', 'chúng ta', 65, 'c'),
('chung minh', 'chúng mình', 60, 'c'),
('cac', 'các', 75, 'c'),

-- ĐỘNG TỪ CƠ BẢN (60+)
('la', 'là', 100, 'l'),
('co', 'có', 100, 'c'),
('khong', 'không', 100, 'k'),
('duoc', 'được', 95, 'd'),
('lam', 'làm', 90, 'l'),
('di', 'đi', 90, 'd'),
('den', 'đến', 85, 'd'),
('ve', 'về', 85, 'v'),
('noi', 'nói', 85, 'n'),
('biet', 'biết', 85, 'b'),
('hieu', 'hiểu', 80, 'h'),
('nghe', 'nghe', 80, 'n'),
('thay', 'thấy', 80, 't'),
('nhin', 'nhìn', 80, 'n'),
('xem', 'xem', 80, 'x'),
('doc', 'đọc', 75, 'd'),
('viet', 'viết', 75, 'v'),
('hoc', 'học', 85, 'h'),
('day', 'dạy', 75, 'd'),
('choi', 'chơi', 75, 'c'),
('an', 'ăn', 85, 'a'),
('uong', 'uống', 80, 'u'),
('ngu', 'ngủ', 75, 'n'),
('thuc', 'thức', 70, 't'),
('cho', 'cho', 85, 'c'),
('lay', 'lấy', 80, 'l'),
('mua', 'mua', 80, 'm'),
('ban', 'bán', 75, 'b'),
('giup', 'giúp', 80, 'g'),
('muon', 'muốn', 85, 'm'),
('can', 'cần', 85, 'c'),
('nen', 'nên', 80, 'n'),
('phai', 'phải', 85, 'p'),
('dung', 'đừng', 75, 'd'),
('hay', 'hãy', 75, 'h'),
('se', 'sẽ', 85, 's'),
('da', 'đã', 85, 'd'),
('dang', 'đang', 85, 'd'),
('roi', 'rồi', 85, 'r'),
('chua', 'chưa', 80, 'c'),
('con', 'còn', 80, 'c'),
('het', 'hết', 75, 'h'),
('nghi', 'nghĩ', 80, 'n'),
('tin', 'tin', 75, 't'),
('song', 'sống', 80, 's'),
('chet', 'chết', 65, 'c'),
('mo', 'mở', 75, 'm'),
('dong', 'đóng', 70, 'd'),
('bat', 'bật', 65, 'b'),
('tat', 'tắt', 65, 't'),
('chay', 'chạy', 75, 'c'),
('nhay', 'nhảy', 65, 'n'),
('boi', 'bơi', 60, 'b'),
('bay', 'bay', 65, 'b'),
('ngoi', 'ngồi', 70, 'n'),
('dung', 'đứng', 70, 'd'),
('nam', 'nằm', 70, 'n'),
('goi', 'gọi', 75, 'g'),
('hoi', 'hỏi', 75, 'h'),
('dap', 'đáp', 65, 'd'),
('gui', 'gửi', 75, 'g'),
('nhan', 'nhận', 75, 'n'),
('doi', 'đợi', 70, 'd'),
('cho', 'chờ', 70, 'c'),
('tim', 'tìm', 80, 't'),
('gap', 'gặp', 75, 'g'),

-- ĐỘNG TỪ TÌNH CẢM (25+)
('yeu', 'yêu', 90, 'y'),
('thuong', 'thương', 80, 't'),
('ghet', 'ghét', 70, 'g'),
('so', 'sợ', 70, 's'),
('vui', 'vui', 80, 'v'),
('buon', 'buồn', 75, 'b'),
('cuoi', 'cười', 75, 'c'),
('khoc', 'khóc', 70, 'k'),
('thich', 'thích', 85, 't'),
('chan', 'chán', 65, 'c'),
('gian', 'giận', 65, 'g'),
('tuc', 'tức', 60, 't'),
('lo', 'lo', 70, 'l'),
('nho', 'nhớ', 80, 'n'),
('quen', 'quên', 70, 'q'),
('cam dong', 'cảm động', 55, 'c'),
('xuc dong', 'xúc động', 55, 'x'),
('nghi ngo', 'nghi ngờ', 55, 'n'),
('ngac nhien', 'ngạc nhiên', 55, 'n'),
('tu hao', 'tự hào', 55, 't'),
('xau ho', 'xấu hổ', 50, 'x'),
('ngai', 'ngại', 60, 'n'),
('dam', 'dám', 60, 'd'),
('mong', 'mong', 65, 'm'),
('uoc', 'ước', 60, 'u'),

-- ĐỘNG TỪ HÀNH ĐỘNG MỞ RỘNG (40+)
('tra loi', 'trả lời', 75, 't'),
('noi chuyen', 'nói chuyện', 75, 'n'),
('tro chuyen', 'trò chuyện', 65, 't'),
('ke', 'kể', 65, 'k'),
('bao', 'bảo', 70, 'b'),
('giao', 'giao', 60, 'g'),
('nhan tin', 'nhắn tin', 70, 'n'),
('goi dien', 'gọi điện', 65, 'g'),
('lien lac', 'liên lạc', 60, 'l'),
('thong bao', 'thông báo', 60, 't'),
('hua', 'hứa', 60, 'h'),
('the', 'thề', 55, 't'),
('di bo', 'đi bộ', 65, 'd'),
('chay bo', 'chạy bộ', 60, 'c'),
('lai xe', 'lái xe', 65, 'l'),
('di chuyen', 'di chuyển', 60, 'd'),
('quay lai', 'quay lại', 65, 'q'),
('tro lai', 'trở lại', 60, 't'),
('roi di', 'rời đi', 55, 'r'),
('buoc', 'bước', 60, 'b'),
('leo', 'leo', 55, 'l'),
('truot', 'trượt', 50, 't'),
('roi', 'rơi', 55, 'r'),
('nga', 'ngã', 55, 'n'),
('dap', 'đạp', 55, 'd'),
('suy nghi', 'suy nghĩ', 75, 's'),
('hoc hoi', 'học hỏi', 60, 'h'),
('tim hieu', 'tìm hiểu', 65, 't'),
('nghien cuu', 'nghiên cứu', 55, 'n'),
('phan tich', 'phân tích', 50, 'p'),
('danh gia', 'đánh giá', 55, 'd'),
('nhan xet', 'nhận xét', 55, 'n'),
('ket luan', 'kết luận', 50, 'k'),
('quyet dinh', 'quyết định', 60, 'q'),
('lua chon', 'lựa chọn', 55, 'l'),
('so sanh', 'so sánh', 55, 's'),
('phan biet', 'phân biệt', 50, 'p'),
('giai quyet', 'giải quyết', 55, 'g'),
('xu ly', 'xử lý', 55, 'x'),
('thuc hien', 'thực hiện', 55, 't'),
('hoan thanh', 'hoàn thành', 60, 'h'),

-- ĐỘNG TỪ SINH HOẠT (30+)
('nau', 'nấu', 65, 'n'),
('nau an', 'nấu ăn', 65, 'n'),
('giat', 'giặt', 55, 'g'),
('phoi', 'phơi', 50, 'p'),
('lau', 'lau', 50, 'l'),
('quet', 'quét', 50, 'q'),
('don dep', 'dọn dẹp', 55, 'd'),
('rua', 'rửa', 60, 'r'),
('tam', 'tắm', 60, 't'),
('mac', 'mặc', 60, 'm'),
('cat', 'cắt', 55, 'c'),
('trong', 'trồng', 50, 't'),
('nuoi', 'nuôi', 55, 'n'),
('cham soc', 'chăm sóc', 60, 'c'),
('lam viec', 'làm việc', 80, 'l'),
('nghi', 'nghỉ', 65, 'n'),
('hop', 'họp', 60, 'h'),
('bao cao', 'báo cáo', 55, 'b'),
('trinh bay', 'trình bày', 50, 't'),
('thao luan', 'thảo luận', 50, 't'),
('de xuat', 'đề xuất', 45, 'd'),
('dong y', 'đồng ý', 65, 'd'),
('tu choi', 'từ chối', 55, 't'),
('chap nhan', 'chấp nhận', 55, 'c'),
('bat dau', 'bắt đầu', 70, 'b'),
('ket thuc', 'kết thúc', 65, 'k'),
('tiep tuc', 'tiếp tục', 65, 't'),
('dung lai', 'dừng lại', 60, 'd'),
('huy', 'hủy', 50, 'h'),
('sua', 'sửa', 60, 's'),
('doi', 'đổi', 60, 'd'),
('thay doi', 'thay đổi', 65, 't'),

-- TÍNH TỪ CƠ BẢN (60+)
('dep', 'đẹp', 80, 'd'),
('xau', 'xấu', 65, 'x'),
('tot', 'tốt', 85, 't'),
('lon', 'lớn', 75, 'l'),
('nho', 'nhỏ', 75, 'n'),
('cao', 'cao', 70, 'c'),
('thap', 'thấp', 65, 't'),
('dai', 'dài', 65, 'd'),
('ngan', 'ngắn', 65, 'n'),
('nong', 'nóng', 65, 'n'),
('lanh', 'lạnh', 65, 'l'),
('nhanh', 'nhanh', 70, 'n'),
('cham', 'chậm', 65, 'c'),
('moi', 'mới', 80, 'm'),
('cu', 'cũ', 65, 'c'),
('tre', 'trẻ', 70, 't'),
('gia', 'già', 65, 'g'),
('kho', 'khó', 75, 'k'),
('de', 'dễ', 75, 'd'),
('nhieu', 'nhiều', 85, 'n'),
('it', 'ít', 70, 'i'),
('day', 'đầy', 65, 'd'),
('trong', 'trống', 60, 't'),
('sang', 'sáng', 70, 's'),
('toi', 'tối', 65, 't'),
('gioi', 'giỏi', 70, 'g'),
('xa', 'xa', 65, 'x'),
('gan', 'gần', 70, 'g'),
('dung', 'đúng', 80, 'd'),
('sai', 'sai', 70, 's'),
('rong', 'rộng', 60, 'r'),
('hep', 'hẹp', 55, 'h'),
('day', 'dày', 50, 'd'),
('mong', 'mỏng', 50, 'm'),
('nang', 'nặng', 60, 'n'),
('nhe', 'nhẹ', 60, 'n'),
('cung', 'cứng', 55, 'c'),
('mem', 'mềm', 55, 'm'),
('kho', 'khô', 55, 'k'),
('uot', 'ướt', 55, 'u'),
('sach', 'sạch', 65, 's'),
('ban', 'bẩn', 55, 'b'),
('thom', 'thơm', 55, 't'),
('ngot', 'ngọt', 55, 'n'),
('chua', 'chua', 55, 'c'),
('man', 'mặn', 50, 'm'),
('cay', 'cay', 55, 'c'),
('dang', 'đắng', 45, 'd'),
('trang', 'trắng', 60, 't'),
('den', 'đen', 60, 'd'),
('do', 'đỏ', 60, 'd'),
('xanh', 'xanh', 65, 'x'),
('vang', 'vàng', 60, 'v'),
('tim', 'tím', 50, 't'),
('hong', 'hồng', 55, 'h'),
('nau', 'nâu', 45, 'n'),
('xam', 'xám', 45, 'x'),
('hay', 'hay', 80, 'h'),
('ngon', 'ngon', 65, 'n'),

-- TÍNH TỪ CẢM XÚC (25+)
('hanh phuc', 'hạnh phúc', 75, 'h'),
('kho chiu', 'khó chịu', 60, 'k'),
('thoai mai', 'thoải mái', 60, 't'),
('lo lang', 'lo lắng', 60, 'l'),
('hoi hop', 'hồi hộp', 55, 'h'),
('sot ruot', 'sốt ruột', 50, 's'),
('bat ngo', 'bất ngờ', 60, 'b'),
('that vong', 'thất vọng', 55, 't'),
('hai long', 'hài lòng', 60, 'h'),
('tu tin', 'tự tin', 60, 't'),
('chan nan', 'chán nản', 50, 'c'),
('met moi', 'mệt mỏi', 60, 'm'),
('khoe', 'khỏe', 70, 'k'),
('yeu', 'yếu', 55, 'y'),
('manh', 'mạnh', 65, 'm'),
('binh tinh', 'bình tĩnh', 55, 'b'),
('nghiem tuc', 'nghiêm túc', 50, 'n'),
('vui ve', 'vui vẻ', 70, 'v'),
('buon ba', 'buồn bã', 50, 'b'),

-- TÍNH TỪ ĐÁNH GIÁ (20+)
('tuyet voi', 'tuyệt vời', 70, 't'),
('te', 'tệ', 55, 't'),
('xuat sac', 'xuất sắc', 55, 'x'),
('binh thuong', 'bình thường', 65, 'b'),
('tam', 'tạm', 55, 't'),
('that', 'thật', 80, 't'),
('gia', 'giả', 55, 'g'),
('chinh', 'chính', 65, 'c'),
('phu', 'phụ', 55, 'p'),
('quan trong', 'quan trọng', 65, 'q'),
('can thiet', 'cần thiết', 55, 'c'),
('dac biet', 'đặc biệt', 60, 'd'),
('pho bien', 'phổ biến', 55, 'p'),
('hien dai', 'hiện đại', 55, 'h'),
('co dien', 'cổ điển', 45, 'c'),
('phuc tap', 'phức tạp', 50, 'p'),
('don gian', 'đơn giản', 60, 'd'),

-- DANH TỪ GIA ĐÌNH (15+)
('nha', 'nhà', 85, 'n'),
('gia dinh', 'gia đình', 80, 'g'),
('bo me', 'bố mẹ', 70, 'b'),
('anh chi em', 'anh chị em', 60, 'a'),
('vo chong', 'vợ chồng', 60, 'v'),
('vo', 'vợ', 65, 'v'),
('chong', 'chồng', 65, 'c'),
('con cai', 'con cái', 60, 'c'),
('con trai', 'con trai', 60, 'c'),
('con gai', 'con gái', 60, 'c'),
('anh trai', 'anh trai', 55, 'a'),
('chi gai', 'chị gái', 55, 'c'),
('em trai', 'em trai', 55, 'e'),
('em gai', 'em gái', 55, 'e'),

-- DANH TỪ TRƯỜNG HỌC (25+)
('truong', 'trường', 80, 't'),
('lop', 'lớp', 75, 'l'),
('truong hoc', 'trường học', 65, 't'),
('dai hoc', 'đại học', 65, 'd'),
('giao vien', 'giáo viên', 60, 'g'),
('hoc sinh', 'học sinh', 65, 'h'),
('sinh vien', 'sinh viên', 65, 's'),
('bai hoc', 'bài học', 60, 'b'),
('bai tap', 'bài tập', 60, 'b'),
('bai thi', 'bài thi', 55, 'b'),
('diem', 'điểm', 65, 'd'),
('lop hoc', 'lớp học', 60, 'l'),
('mon hoc', 'môn học', 55, 'm'),
('thi', 'thi', 60, 't'),
('ket qua', 'kết quả', 70, 'k'),
('van de', 'vấn đề', 70, 'v'),
('tieu hoc', 'tiểu học', 55, 't'),
('trung hoc', 'trung học', 55, 't'),
('pho thong', 'phổ thông', 50, 'p'),
('cao dang', 'cao đẳng', 50, 'c'),
('thac si', 'thạc sĩ', 45, 't'),
('tien si', 'tiến sĩ', 45, 't'),
('cu nhan', 'cử nhân', 45, 'c'),
('bang cap', 'bằng cấp', 45, 'b'),
('hoc bong', 'học bổng', 50, 'h'),

-- DANH TỪ NƠI CHỐN (35+)
('phong', 'phòng', 70, 'p'),
('cua hang', 'cửa hàng', 60, 'c'),
('cho', 'chợ', 55, 'c'),
('benh vien', 'bệnh viện', 60, 'b'),
('nha hang', 'nhà hàng', 60, 'n'),
('quan', 'quán', 60, 'q'),
('sieu thi', 'siêu thị', 60, 's'),
('cong ty', 'công ty', 65, 'c'),
('van phong', 'văn phòng', 60, 'v'),
('nha may', 'nhà máy', 50, 'n'),
('thanh pho', 'thành phố', 65, 't'),
('nong thon', 'nông thôn', 50, 'n'),
('bien', 'biển', 55, 'b'),
('nui', 'núi', 50, 'n'),
('rung', 'rừng', 50, 'r'),
('song', 'sông', 55, 's'),
('ho', 'hồ', 50, 'h'),
('duong', 'đường', 75, 'd'),
('cau', 'cầu', 55, 'c'),
('cong vien', 'công viên', 55, 'c'),
('san bay', 'sân bay', 50, 's'),
('ben xe', 'bến xe', 50, 'b'),
('nha tho', 'nhà thờ', 45, 'n'),
('chua', 'chùa', 45, 'c'),
('nuoc', 'nước', 80, 'n'),
('tinh', 'tỉnh', 55, 't'),
('huyen', 'huyện', 50, 'h'),
('xa', 'xã', 50, 'x'),
('phuong', 'phường', 55, 'p'),
('quan', 'quận', 55, 'q'),
('lang', 'làng', 50, 'l'),
('pho', 'phố', 55, 'p'),
('ngo', 'ngõ', 45, 'n'),
('hem', 'hẻm', 45, 'h'),

-- DANH TỪ ĐỒ VẬT (35+)
('xe', 'xe', 70, 'x'),
('xe may', 'xe máy', 60, 'x'),
('oto', 'ô tô', 55, 'o'),
('xe dap', 'xe đạp', 50, 'x'),
('dien thoai', 'điện thoại', 70, 'd'),
('may tinh', 'máy tính', 65, 'm'),
('laptop', 'laptop', 55, 'l'),
('tivi', 'tivi', 50, 't'),
('sach', 'sách', 75, 's'),
('but', 'bút', 65, 'b'),
('vo', 'vở', 60, 'v'),
('ban', 'bàn', 65, 'b'),
('ghe', 'ghế', 60, 'g'),
('cua', 'cửa', 65, 'c'),
('giuong', 'giường', 55, 'g'),
('tu', 'tủ', 50, 't'),
('ao', 'áo', 65, 'a'),
('quan', 'quần', 65, 'q'),
('giay', 'giày', 60, 'g'),
('dep', 'dép', 50, 'd'),
('non', 'nón', 45, 'n'),
('mu', 'mũ', 45, 'm'),
('kinh', 'kính', 50, 'k'),
('dong ho', 'đồng hồ', 55, 'd'),
('vi', 'ví', 45, 'v'),
('tui', 'túi', 50, 't'),
('ba lo', 'ba lô', 50, 'b'),
('balo', 'ba lô', 50, 'b'),
('may anh', 'máy ảnh', 50, 'm'),
('tai nghe', 'tai nghe', 50, 't'),
('coc', 'cốc', 45, 'c'),
('ly', 'ly', 45, 'l'),
('chen', 'chén', 40, 'c'),
('bat', 'bát', 45, 'b'),
('dia', 'đĩa', 40, 'd'),

-- DANH TỪ THỜI GIAN (30+)
('ngay', 'ngày', 80, 'n'),
('dem', 'đêm', 65, 'd'),
('sang', 'sáng', 70, 's'),
('chieu', 'chiều', 65, 'c'),
('trua', 'trưa', 60, 't'),
('toi', 'tối', 65, 't'),
('gio', 'giờ', 70, 'g'),
('phut', 'phút', 60, 'p'),
('giay', 'giây', 55, 'g'),
('nam', 'năm', 75, 'n'),
('thang', 'tháng', 70, 't'),
('tuan', 'tuần', 65, 't'),
('hom nay', 'hôm nay', 75, 'h'),
('hom qua', 'hôm qua', 65, 'h'),
('ngay mai', 'ngày mai', 70, 'n'),
('tuan truoc', 'tuần trước', 50, 't'),
('tuan sau', 'tuần sau', 50, 't'),
('thang truoc', 'tháng trước', 45, 't'),
('thang sau', 'tháng sau', 45, 't'),
('nam truoc', 'năm trước', 45, 'n'),
('nam sau', 'năm sau', 45, 'n'),
('bao gio', 'bao giờ', 65, 'b'),
('luc nao', 'lúc nào', 60, 'l'),
('khi nao', 'khi nào', 60, 'k'),
('mua', 'mùa', 50, 'm'),
('mua xuan', 'mùa xuân', 50, 'm'),
('mua ha', 'mùa hạ', 45, 'm'),
('mua thu', 'mùa thu', 50, 'm'),
('mua dong', 'mùa đông', 50, 'm'),

-- DANH TỪ CƠ THỂ (20+)
('mat', 'mắt', 65, 'm'),
('tai', 'tai', 60, 't'),
('mui', 'mũi', 55, 'm'),
('mieng', 'miệng', 55, 'm'),
('tay', 'tay', 65, 't'),
('chan', 'chân', 65, 'c'),
('dau', 'đầu', 70, 'd'),
('long', 'lòng', 65, 'l'),
('trai tim', 'trái tim', 70, 't'),
('mat', 'mặt', 65, 'm'),
('lung', 'lưng', 50, 'l'),
('vai', 'vai', 50, 'v'),
('bung', 'bụng', 50, 'b'),
('co', 'cổ', 50, 'c'),
('toc', 'tóc', 55, 't'),
('rang', 'răng', 50, 'r'),
('moi', 'môi', 50, 'm'),
('da', 'da', 50, 'd'),
('xuong', 'xương', 45, 'x'),

-- DANH TỪ ĐỒ ĂN / ĐỒ UỐNG (30+)
('com', 'cơm', 70, 'c'),
('pho', 'phở', 60, 'p'),
('bun', 'bún', 55, 'b'),
('mi', 'mì', 55, 'm'),
('banh mi', 'bánh mì', 55, 'b'),
('banh', 'bánh', 55, 'b'),
('xoi', 'xôi', 45, 'x'),
('thit', 'thịt', 55, 't'),
('ca', 'cá', 55, 'c'),
('rau', 'rau', 55, 'r'),
('trai cay', 'trái cây', 50, 't'),
('nuoc', 'nước', 80, 'n'),
('tra', 'trà', 55, 't'),
('ca phe', 'cà phê', 60, 'c'),
('sua', 'sữa', 55, 's'),
('bia', 'bia', 45, 'b'),
('ruou', 'rượu', 45, 'r'),
('nuoc ngot', 'nước ngọt', 45, 'n'),
('kem', 'kem', 45, 'k'),
('do an', 'đồ ăn', 60, 'd'),
('mon an', 'món ăn', 55, 'm'),
('trung', 'trứng', 50, 't'),
('chao', 'cháo', 50, 'c'),
('bap', 'bắp', 40, 'b'),
('khoai', 'khoai', 45, 'k'),
('dau', 'đậu', 45, 'd'),

-- DANH TỪ TIỀN BẠC / CÔNG VIỆC (20+)
('tien', 'tiền', 75, 't'),
('viec', 'việc', 80, 'v'),
('luong', 'lương', 55, 'l'),
('gia', 'giá', 60, 'g'),
('phi', 'phí', 50, 'p'),
('mien phi', 'miễn phí', 55, 'm'),
('dat', 'đắt', 55, 'd'),
('re', 'rẻ', 55, 'r'),
('nghe', 'nghề', 50, 'n'),
('cong viec', 'công việc', 75, 'c'),
('thu nhap', 'thu nhập', 50, 't'),
('chi phi', 'chi phí', 50, 'c'),
('lai', 'lãi', 45, 'l'),
('lo', 'lỗ', 45, 'l'),
('von', 'vốn', 50, 'v'),
('doanh thu', 'doanh thu', 45, 'd'),
('loi nhuan', 'lợi nhuận', 45, 'l'),

-- DANH TỪ THIÊN NHIÊN / THỜI TIẾT (20+)
('troi', 'trời', 70, 't'),
('dat', 'đất', 55, 'd'),
('mua', 'mưa', 60, 'm'),
('nang', 'nắng', 55, 'n'),
('gio', 'gió', 55, 'g'),
('may', 'mây', 50, 'm'),
('mat', 'mát', 55, 'm'),
('am', 'ấm', 50, 'a'),
('sam', 'sấm', 40, 's'),
('chop', 'chớp', 40, 'c'),
('bao', 'bão', 45, 'b'),
('lu', 'lũ', 40, 'l'),
('han', 'hạn', 40, 'h'),
('tuyet', 'tuyết', 40, 't'),
('suong', 'sương', 40, 's'),

-- TRẠNG TỪ / LIÊN TỪ / PHÓ TỪ (60+)
('rat', 'rất', 85, 'r'),
('cung', 'cũng', 85, 'c'),
('thi', 'thì', 80, 't'),
('ma', 'mà', 80, 'm'),
('vi', 'vì', 75, 'v'),
('nhung', 'nhưng', 85, 'n'),
('va', 'và', 90, 'v'),
('hoac', 'hoặc', 70, 'h'),
('neu', 'nếu', 75, 'n'),
('khi', 'khi', 80, 'k'),
('luc', 'lúc', 70, 'l'),
('luon', 'luôn', 75, 'l'),
('thuong', 'thường', 70, 't'),
('som', 'sớm', 60, 's'),
('muon', 'muộn', 55, 'm'),
('qua', 'quá', 75, 'q'),
('lam', 'lắm', 70, 'l'),
('the', 'thế', 75, 't'),
('nay', 'này', 80, 'n'),
('do', 'đó', 75, 'd'),
('kia', 'kia', 60, 'k'),
('day', 'đây', 80, 'd'),
('o', 'ở', 80, 'o'),
('tren', 'trên', 75, 't'),
('duoi', 'dưới', 70, 'd'),
('trong', 'trong', 80, 't'),
('ngoai', 'ngoài', 70, 'n'),
('truoc', 'trước', 70, 't'),
('sau', 'sau', 70, 's'),
('giua', 'giữa', 60, 'g'),
('ben', 'bên', 65, 'b'),
('canh', 'cạnh', 55, 'c'),
('cuc ky', 'cực kỳ', 60, 'c'),
('vo cung', 'vô cùng', 55, 'v'),
('het suc', 'hết sức', 50, 'h'),
('kha', 'khá', 65, 'k'),
('tuong doi', 'tương đối', 50, 't'),
('hoi', 'hơi', 60, 'h'),
('vua', 'vừa', 65, 'v'),
('sap', 'sắp', 65, 's'),
('lien tuc', 'liên tục', 50, 'l'),
('thuong xuyen', 'thường xuyên', 50, 't'),
('doi khi', 'đôi khi', 55, 'd'),
('thinh thoang', 'thỉnh thoảng', 50, 't'),
('luon luon', 'luôn luôn', 55, 'l'),
('boi vi', 'bởi vì', 60, 'b'),
('cho nen', 'cho nên', 55, 'c'),
('vi vay', 'vì vậy', 55, 'v'),
('tuy nhien', 'tuy nhiên', 55, 't'),
('mac du', 'mặc dù', 50, 'm'),
('nhung ma', 'nhưng mà', 60, 'n'),
('hay la', 'hay là', 55, 'h'),

-- SỐ ĐẾM (20+)
('mot', 'một', 85, 'm'),
('hai', 'hai', 80, 'h'),
('ba', 'ba', 80, 'b'),
('bon', 'bốn', 70, 'b'),
('nam', 'năm', 75, 'n'),
('sau', 'sáu', 65, 's'),
('bay', 'bảy', 65, 'b'),
('tam', 'tám', 60, 't'),
('chin', 'chín', 60, 'c'),
('muoi', 'mười', 65, 'm'),
('tram', 'trăm', 60, 't'),
('nghin', 'nghìn', 55, 'n'),
('van', 'vạn', 45, 'v'),
('trieu', 'triệu', 50, 't'),
('ty', 'tỷ', 45, 't'),
('thu nhat', 'thứ nhất', 55, 't'),
('thu hai', 'thứ hai', 55, 't'),
('thu ba', 'thứ ba', 50, 't'),

-- TỪ THÔNG DỤNG KHÁC (80+)
('xin', 'xin', 70, 'x'),
('cam on', 'cảm ơn', 80, 'c'),
('xin loi', 'xin lỗi', 75, 'x'),
('chao', 'chào', 75, 'c'),
('tam biet', 'tạm biệt', 65, 't'),
('vang', 'vâng', 65, 'v'),
('da', 'dạ', 70, 'd'),
('u', 'ừ', 65, 'u'),
('nhe', 'nhé', 75, 'n'),
('nha', 'nha', 70, 'n'),
('gi', 'gì', 80, 'g'),
('nao', 'nào', 75, 'n'),
('dau', 'đâu', 75, 'd'),
('tai sao', 'tại sao', 70, 't'),
('the nao', 'thế nào', 70, 't'),
('may', 'mấy', 65, 'm'),
('oi', 'ơi', 75, 'o'),
('nhi', 'nhỉ', 60, 'n'),
('ha', 'hả', 50, 'h'),
('chu', 'chứ', 60, 'c'),
('cua', 'của', 90, 'c'),
('voi', 'với', 85, 'v'),
('de', 'để', 80, 'd'),
('nhu', 'như', 80, 'n'),
('theo', 'theo', 70, 't'),
('bang', 'bằng', 65, 'b'),
('tu', 'từ', 70, 't'),
('ra', 'ra', 75, 'r'),
('vao', 'vào', 75, 'v'),
('len', 'lên', 75, 'l'),
('xuong', 'xuống', 65, 'x'),
('nhat', 'nhất', 80, 'n'),
('met', 'mệt', 65, 'm'),
('duoc', 'được', 95, 'd'),
('sao', 'sao', 70, 's'),
('cai', 'cái', 75, 'c'),
('nay', 'nầy', 55, 'n'),
('viec', 'việc', 80, 'v'),

-- TỪ GHÉP PHỔ BIẾN (40+)
('cuoc song', 'cuộc sống', 75, 'c'),
('ban be', 'bạn bè', 70, 'b'),
('nguoi yeu', 'người yêu', 70, 'n'),
('quan ao', 'quần áo', 60, 'q'),
('ban than', 'bạn thân', 65, 'b'),
('dong nghiep', 'đồng nghiệp', 55, 'd'),
('ban hoc', 'bạn học', 60, 'b'),
('tinh yeu', 'tình yêu', 65, 't'),
('su that', 'sự thật', 55, 's'),
('y kien', 'ý kiến', 55, 'y'),
('the gioi', 'thế giới', 60, 't'),
('xa hoi', 'xã hội', 55, 'x'),
('van hoa', 'văn hóa', 50, 'v'),
('lich su', 'lịch sử', 50, 'l'),
('khoa hoc', 'khoa học', 55, 'k'),
('cong nghe', 'công nghệ', 60, 'c'),
('suc khoe', 'sức khỏe', 60, 's'),
('thu do', 'thủ đô', 50, 't'),
('que huong', 'quê hương', 55, 'q'),
('to quoc', 'tổ quốc', 50, 't'),
('dan toc', 'dân tộc', 50, 'd'),
('chinh phu', 'chính phủ', 50, 'c'),
('nhan dan', 'nhân dân', 50, 'n'),
('quoc gia', 'quốc gia', 50, 'q'),
('xa hoi', 'xã hội', 55, 'x'),
('kinh te', 'kinh tế', 55, 'k'),
('giao duc', 'giáo dục', 55, 'g'),
('y te', 'y tế', 50, 'y'),
('an ninh', 'an ninh', 50, 'a'),
('quoc phong', 'quốc phòng', 45, 'q'),
('hop tac', 'hợp tác', 50, 'h'),
('phat trien', 'phát triển', 55, 'p'),
('doi moi', 'đổi mới', 50, 'd'),
('sang tao', 'sáng tạo', 50, 's'),

-- TỪ CÔNG NGHỆ / INTERNET (30+)
('mang', 'mạng', 55, 'm'),
('mang xa hoi', 'mạng xã hội', 55, 'm'),
('ung dung', 'ứng dụng', 55, 'u'),
('phan mem', 'phần mềm', 50, 'p'),
('trang web', 'trang web', 50, 't'),
('tai khoan', 'tài khoản', 55, 't'),
('mat khau', 'mật khẩu', 50, 'm'),
('dang nhap', 'đăng nhập', 50, 'd'),
('dang ky', 'đăng ký', 55, 'd'),
('cap nhat', 'cập nhật', 50, 'c'),
('tai xuong', 'tải xuống', 45, 't'),
('chia se', 'chia sẻ', 60, 'c'),
('binh luan', 'bình luận', 55, 'b'),
('tin nhan', 'tin nhắn', 55, 't'),
('hinh anh', 'hình ảnh', 55, 'h'),
('video', 'video', 55, 'v'),
('livestream', 'livestream', 40, 'l'),
('online', 'online', 50, 'o'),
('offline', 'offline', 40, 'o'),
('wifi', 'wifi', 50, 'w'),
('du lieu', 'dữ liệu', 45, 'd'),
('he thong', 'hệ thống', 50, 'h'),
('thiet bi', 'thiết bị', 50, 't'),
('man hinh', 'màn hình', 50, 'm'),
('ban phim', 'bàn phím', 45, 'b'),
('chuot', 'chuột', 45, 'c'),
('sac', 'sạc', 45, 's'),
('pin', 'pin', 45, 'p'),

-- TỪ Y TẾ / SỨC KHỎE (20+)
('benh', 'bệnh', 55, 'b'),
('thuoc', 'thuốc', 55, 't'),
('bac si', 'bác sĩ', 60, 'b'),
('y ta', 'y tá', 45, 'y'),
('kham', 'khám', 50, 'k'),
('chua benh', 'chữa bệnh', 50, 'c'),
('sot', 'sốt', 50, 's'),
('ho', 'ho', 45, 'h'),
('dau', 'đau', 55, 'd'),
('cam', 'cảm', 45, 'c'),
('cum', 'cúm', 40, 'c'),
('di ung', 'dị ứng', 40, 'd'),
('phau thuat', 'phẫu thuật', 40, 'p'),
('tiem', 'tiêm', 45, 't'),
('xet nghiem', 'xét nghiệm', 45, 'x'),
('tam ly', 'tâm lý', 50, 't'),
('stress', 'stress', 40, 's'),

-- TỪ GIAO THÔNG (15+)
('xe buyt', 'xe buýt', 50, 'x'),
('tau', 'tàu', 50, 't'),
('may bay', 'máy bay', 55, 'm'),
('tau hoa', 'tàu hỏa', 45, 't'),
('taxi', 'taxi', 50, 't'),
('xe om', 'xe ôm', 45, 'x'),
('giao thong', 'giao thông', 50, 'g'),
('duong pho', 'đường phố', 50, 'd'),
('nga tu', 'ngã tư', 45, 'n'),
('den xanh', 'đèn xanh', 45, 'd'),
('den do', 'đèn đỏ', 45, 'd'),
('ket xe', 'kẹt xe', 50, 'k'),
('tai nan', 'tai nạn', 50, 't'),

-- TỪ THỂ THAO (15+)
('bong da', 'bóng đá', 55, 'b'),
('bong ro', 'bóng rổ', 40, 'b'),
('cau long', 'cầu lông', 45, 'c'),
('boi loi', 'bơi lội', 40, 'b'),
('chay bo', 'chạy bộ', 50, 'c'),
('the duc', 'thể dục', 50, 't'),
('the thao', 'thể thao', 55, 't'),
('tran dau', 'trận đấu', 45, 't'),
('vo dich', 'vô địch', 45, 'v'),
('giai thuong', 'giải thưởng', 45, 'g'),
('huy chuong', 'huy chương', 40, 'h'),
('hlv', 'huấn luyện viên', 35, 'h'),
('cau thu', 'cầu thủ', 45, 'c'),
('doi tuyen', 'đội tuyển', 45, 'd'),
('san van dong', 'sân vận động', 40, 's'),

-- TỪ BỔ SUNG THƯỜNG GẶP TRONG TEENCODE (80+)
-- Các từ hay bị thiếu khi bỏ ký tự lặp
('thieu', 'thiếu', 65, 't'),
('thoi', 'thôi', 70, 't'),
('xong', 'xong', 70, 'x'),
('ngon', 'ngon', 65, 'n'),
('tha', 'tha', 50, 't'),
('tho', 'thơ', 50, 't'),
('phai', 'phải', 85, 'p'),
('muon', 'muốn', 85, 'm'),
('hom', 'hôm', 65, 'h'),
('lau', 'lâu', 55, 'l'),
('lan', 'lần', 55, 'l'),
('chiu', 'chịu', 60, 'c'),
('nhau', 'nhau', 65, 'n'),
('mai', 'mai', 70, 'm'),
('roi', 'rồi', 85, 'r'),
('vay', 'vậy', 75, 'v'),
('khong', 'không', 100, 'k'),
('on', 'ôn', 50, 'o'),
('du', 'đủ', 60, 'd'),
('yen', 'yên', 55, 'y'),
('kieu', 'kiểu', 50, 'k'),
('dieu', 'điều', 55, 'd'),
('lieu', 'liệu', 50, 'l'),
('phieu', 'phiếu', 45, 'p'),
('nhieu', 'nhiều', 85, 'n'),
('chieu', 'chiều', 65, 'c'),
('hieu', 'hiểu', 80, 'h'),
('chuyen', 'chuyện', 70, 'c'),
('tuyen', 'tuyến', 50, 't'),
('huyen', 'huyện', 50, 'h'),
('nguyen', 'nguyện', 50, 'n'),
('suong', 'sướng', 50, 's'),
('ruou', 'rượu', 45, 'r'),
('muoi', 'mười', 65, 'm'),
('tuoi', 'tuổi', 60, 't'),
('cuoi', 'cười', 75, 'c'),
('duoi', 'dưới', 70, 'd'),
('nuoi', 'nuôi', 55, 'n'),
('buoi', 'buổi', 60, 'b'),
('suot', 'suốt', 50, 's'),
('muot', 'mượt', 40, 'm'),
('tuot', 'tuột', 40, 't'),
('luot', 'lượt', 45, 'l'),
('quyet', 'quyết', 55, 'q'),
('huyet', 'huyết', 40, 'h'),
('thuyet', 'thuyết', 45, 't'),
('tuyet', 'tuyệt', 55, 't'),
('chuyet', 'chuyệt', 35, 'c'),
('lac', 'lạc', 50, 'l'),
('bac', 'bạc', 45, 'b'),
('sac', 'sắc', 50, 's'),
('mac', 'mặc', 60, 'm'),
('giac', 'giấc', 50, 'g'),
('nhe', 'nhé', 75, 'n'),
('nghe', 'nghe', 80, 'n'),
('nghe', 'nghệ', 50, 'n'),
('gheo', 'ghẹo', 35, 'g'),
('ghep', 'ghép', 40, 'g'),
('phe', 'phê', 45, 'p'),
('que', 'quê', 50, 'q'),
('quen', 'quen', 60, 'q'),
('hen', 'hẹn', 60, 'h'),
('ren', 'rèn', 40, 'r'),
('nen', 'nên', 80, 'n'),
('len', 'lên', 75, 'l'),
('kem', 'kém', 50, 'k'),
('dem', 'đếm', 45, 'd'),
('nem', 'ném', 45, 'n'),
('rem', 'rèm', 35, 'r'),
('beo', 'béo', 45, 'b'),
('keo', 'kéo', 50, 'k'),
('leo', 'leo', 55, 'l'),
('meo', 'mèo', 50, 'm'),
('heo', 'heo', 45, 'h'),
('deo', 'đeo', 45, 'd'),
('ngao', 'ngào', 40, 'n'),
('gao', 'gạo', 50, 'g'),
('dao', 'dao', 50, 'd'),
('sao', 'sao', 70, 's'),
('nao', 'nào', 75, 'n'),
('tao', 'tạo', 55, 't');


-- ============================================================
-- 2. ABBREVIATIONS (~500+ từ viết tắt)
-- ============================================================

INSERT INTO `abbreviations` (`abbreviation`, `full_word`, `full_word_accent`, `priority`) VALUES
-- TEENCODE PHỔ BIẾN NHẤT - KHÔNG
('k', 'khong', 'không', 10),
('ko', 'khong', 'không', 9),
('kg', 'khong', 'không', 8),
('hk', 'khong', 'không', 7),
('kh', 'khong', 'không', 7),
('khg', 'khong', 'không', 7),
('hem', 'khong', 'không', 6),
('hông', 'khong', 'không', 6),
('hog', 'khong', 'không', 5),
('k0', 'khong', 'không', 6),
('kng', 'khong', 'không', 5),
('khoong', 'khong', 'không', 5),
('khôg', 'khong', 'không', 5),

-- CỤM KHÔNG + ...
('kp', 'khong phai', 'không phải', 7),
('kb', 'khong biet', 'không biết', 7),
('kc', 'khong co', 'không có', 6),
('kdc', 'khong duoc', 'không được', 6),
('kt', 'khong the', 'không thể', 5),
('ks', 'khong sao', 'không sao', 5),

-- ĐƯỢC
('dc', 'duoc', 'được', 10),
('đc', 'duoc', 'được', 10),
('dk', 'duoc', 'được', 8),
('đk', 'duoc', 'được', 8),
('dck', 'duoc khong', 'được không', 6),
('đck', 'duoc khong', 'được không', 6),

-- YÊU
('iu', 'yeu', 'yêu', 10),
('iuu', 'yeu', 'yêu', 9),
('iuuu', 'yeu', 'yêu', 8),
('y', 'yeu', 'yêu', 7),
('iu lm', 'yeu lam', 'yêu lắm', 7),

-- ĐẠI TỪ VIẾT TẮT
('t', 'toi', 'tôi', 8),
('m', 'may', 'mày', 6),
('a', 'anh', 'anh', 7),
('e', 'em', 'em', 7),
('mk', 'minh', 'mình', 9),
('mik', 'minh', 'mình', 8),
('mh', 'minh', 'mình', 7),
('tui', 'toi', 'tôi', 8),
('bn', 'ban', 'bạn', 9),
('b', 'ban', 'bạn', 6),
('ng', 'nguoi', 'người', 7),
('ngta', 'nguoi ta', 'người ta', 6),
('nk', 'nguoi khac', 'người khác', 5),
('mn', 'moi nguoi', 'mọi người', 7),
('ck', 'chong', 'chồng', 6),
('vk', 'vo', 'vợ', 6),
('ny', 'nguoi yeu', 'người yêu', 7),
('bff', 'ban than', 'bạn thân', 6),
('gf', 'ban gai', 'bạn gái', 5),
('bf', 'ban trai', 'bạn trai', 5),

-- ĐỘNG TỪ VIẾT TẮT
('ns', 'noi', 'nói', 9),
('bt', 'biet', 'biết', 8),
('bk', 'biet', 'biết', 7),
('bik', 'biet', 'biết', 6),
('bít', 'biet', 'biết', 6),
('hiu', 'hieu', 'hiểu', 7),
('r', 'roi', 'rồi', 8),
('oy', 'roi', 'rồi', 6),
('rui', 'roi', 'rồi', 6),
('ròi', 'roi', 'rồi', 6),
('ik', 'di', 'đi', 7),
('đi', 'di', 'đi', 8),
('vs', 'voi', 'với', 8),
('lm', 'lam', 'làm', 8),
('ms', 'moi', 'mới', 7),
('trc', 'truoc', 'trước', 8),
('trog', 'trong', 'trong', 6),
('lun', 'luon', 'luôn', 8),
('thik', 'thich', 'thích', 8),
('thíck', 'thich', 'thích', 7),
('ths', 'thich', 'thích', 6),
('tks', 'cam on', 'cảm ơn', 7),
('thanks', 'cam on', 'cảm ơn', 7),
('thank', 'cam on', 'cảm ơn', 6),
('tk', 'cam on', 'cảm ơn', 5),
('xl', 'xin loi', 'xin lỗi', 7),
('sorry', 'xin loi', 'xin lỗi', 6),
('sr', 'xin loi', 'xin lỗi', 6),
('sry', 'xin loi', 'xin lỗi', 6),
('xk', 'xin loi', 'xin lỗi', 5),

-- TÍNH TỪ VIẾT TẮT
('đp', 'dep', 'đẹp', 7),
('nh', 'nho', 'nhỏ', 5),
('ln', 'lon', 'lớn', 5),
('nnh', 'nhanh', 'nhanh', 5),
('nhiu', 'nhieu', 'nhiều', 7),
('nhìu', 'nhieu', 'nhiều', 7),
('bth', 'binh thuong', 'bình thường', 6),
('bt', 'binh thuong', 'bình thường', 5),

-- TRẠNG TỪ / PHÓ TỪ VIẾT TẮT
('cx', 'cung', 'cũng', 8),
('cg', 'cung', 'cũng', 7),
('j', 'gi', 'gì', 9),
('z', 'vay', 'vậy', 8),
('v', 'vay', 'vậy', 7),
('dz', 'vay', 'vậy', 6),
('zậy', 'vay', 'vậy', 6),
('vậy', 'vay', 'vậy', 6),
('ntn', 'nhu the nao', 'như thế nào', 7),
('wa', 'qua', 'quá', 6),
('wá', 'qua', 'quá', 6),
('quá', 'qua', 'quá', 6),
('chx', 'chua', 'chưa', 7),
('chs', 'chua', 'chưa', 6),
('ch', 'chua', 'chưa', 5),

-- OK / ĐỒNG Ý
('ok', 'dong y', 'đồng ý', 7),
('oke', 'dong y', 'đồng ý', 7),
('okie', 'dong y', 'đồng ý', 6),
('okê', 'dong y', 'đồng ý', 6),
('oce', 'dong y', 'đồng ý', 5),
('oki', 'dong y', 'đồng ý', 6),

-- THỜI GIAN VIẾT TẮT
('hm', 'hom', 'hôm', 6),
('hn', 'hom nay', 'hôm nay', 7),
('hqua', 'hom qua', 'hôm qua', 6),
('bjo', 'bay gio', 'bây giờ', 7),
('bjờ', 'bay gio', 'bây giờ', 7),
('bh', 'bay gio', 'bây giờ', 6),
('bâyh', 'bay gio', 'bây giờ', 5),
('bgờ', 'bay gio', 'bây giờ', 5),
('h', 'gio', 'giờ', 5),
('sn', 'sinh nhat', 'sinh nhật', 6),
('t2', 'thu hai', 'thứ hai', 5),
('t3', 'thu ba', 'thứ ba', 5),
('t4', 'thu tu', 'thứ tư', 5),
('t5', 'thu nam', 'thứ năm', 5),
('t6', 'thu sau', 'thứ sáu', 5),
('t7', 'thu bay', 'thứ bảy', 5),
('cn', 'chu nhat', 'chủ nhật', 5),

-- NƠI CHỐN / TỔ CHỨC
('nc', 'noi chuyen', 'nói chuyện', 7),
('nt', 'nhan tin', 'nhắn tin', 7),
('dt', 'dien thoai', 'điện thoại', 7),
('đt', 'dien thoai', 'điện thoại', 6),
('fb', 'facebook', 'facebook', 6),
('ib', 'inbox', 'inbox', 6),
('tt', 'trang thai', 'trạng thái', 5),
('gd', 'gia dinh', 'gia đình', 6),
('gđ', 'gia dinh', 'gia đình', 6),
('sv', 'sinh vien', 'sinh viên', 6),
('gv', 'giao vien', 'giáo viên', 6),
('hs', 'hoc sinh', 'học sinh', 6),
('đh', 'dai hoc', 'đại học', 6),
('th', 'tieu hoc', 'tiểu học', 4),
('thcs', 'trung hoc co so', 'trung học cơ sở', 5),
('thpt', 'trung hoc pho thong', 'trung học phổ thông', 5),

-- ĐỊA DANH
('sg', 'sai gon', 'sài gòn', 5),
('tp', 'thanh pho', 'thành phố', 5),
('q', 'quan', 'quận', 4),
('p', 'phuong', 'phường', 4),
('dn', 'da nang', 'đà nẵng', 4),
('bd', 'binh duong', 'bình dương', 4),
('hcm', 'ho chi minh', 'hồ chí minh', 5),
('hp', 'hai phong', 'hải phòng', 4),
('ct', 'can tho', 'cần thơ', 4),
('nt', 'nha trang', 'nha trang', 4),
('dl', 'da lat', 'đà lạt', 4),
('vt', 'vung tau', 'vũng tàu', 4),

-- VIẾT TẮT HÀNH ĐỘNG
('tl', 'tra loi', 'trả lời', 6),
('rep', 'tra loi', 'trả lời', 6),
('ss', 'so sanh', 'so sánh', 5),
('kq', 'ket qua', 'kết quả', 5),
('nma', 'nhung ma', 'nhưng mà', 6),
('dag', 'dang', 'đang', 6),
('tg', 'thoi gian', 'thời gian', 5),
('mt', 'may tinh', 'máy tính', 5),
('ktra', 'kiem tra', 'kiểm tra', 5),
('kthi', 'ky thi', 'kỳ thi', 5),
('btvn', 'bai tap ve nha', 'bài tập về nhà', 5),

-- TEENCODE TIẾNG LÓNG
('ak', 'a', 'à', 6),
('uk', 'u', 'ừ', 6),
('uh', 'u', 'ừ', 5),
('uhm', 'u', 'ừ', 5),
('ùm', 'u', 'ừ', 5),
('haha', 'ha ha', 'ha ha', 5),
('hihi', 'hi hi', 'hi hi', 5),
('huhu', 'hu hu', 'hu hu', 5),
('hehe', 'he he', 'he he', 5),
('kk', 'ha ha', 'ha ha', 4),
('zui', 'vui', 'vui', 6),
('bùn', 'buon', 'buồn', 6),
('lém', 'lam', 'lắm', 5),
('nè', 'nay', 'này', 6),
('ni', 'nay', 'này', 6),
('hen', 'hen', 'hẹn', 6),
('nge', 'nghe', 'nghe', 6),
('ghe', 'ghet', 'ghét', 5),
('trg', 'truong', 'trường', 5),
('đog', 'dong', 'đóng', 5),
('ngoy', 'ngoai', 'ngoài', 5),

-- VIẾT TẮT INTERNET
('cmt', 'binh luan', 'bình luận', 5),
('like', 'thich', 'thích', 5),
('share', 'chia se', 'chia sẻ', 5),
('sub', 'dang ky', 'đăng ký', 4),
('acc', 'tai khoan', 'tài khoản', 4),
('pass', 'mat khau', 'mật khẩu', 4),
('link', 'duong dan', 'đường dẫn', 4),
('pic', 'hinh anh', 'hình ảnh', 4),
('ad', 'admin', 'admin', 4),
('mod', 'quan ly', 'quản lý', 4),
('pls', 'xin', 'xin', 5),
('plz', 'xin', 'xin', 5),
('np', 'khong co gi', 'không có gì', 4),
('wtf', 'cai gi', 'cái gì', 3),
('omg', 'troi oi', 'trời ơi', 4),
('brb', 'quay lai ngay', 'quay lại ngay', 3),
('btw', 'nhan tien', 'nhân tiện', 3),
('lol', 'cuoi', 'cười', 4),

-- MỞ RỘNG TEENCODE GEN Z
('xg', 'xong', 'xong', 6),
('tml', 'thuong minh lam', 'thương mình lắm', 5),
('ctrai', 'con trai', 'con trai', 4),
('cgai', 'con gai', 'con gái', 4),
('wc', 'nha ve sinh', 'nhà vệ sinh', 4),
('sp', 'san pham', 'sản phẩm', 4),
('đn', 'di ngu', 'đi ngủ', 5),
('gm', 'good morning', 'chào buổi sáng', 3),
('gn', 'good night', 'chúc ngủ ngon', 3),
('cko', 'cho khong', 'cho không', 5),
('đag', 'dang', 'đang', 6),
('rr', 'roi roi', 'rồi rồi', 4),
('cc', 'cac', 'các', 4),
('ng2', 'nguoi ấy', 'người ấy', 4),
('cmn', 'cua minh', 'của mình', 5),
('dm', 'di', 'đi', 3),

-- VIẾT TẮT CHUYÊN NGÀNH
('cntt', 'cong nghe thong tin', 'công nghệ thông tin', 5),
('ktqd', 'kinh te quoc dan', 'kinh tế quốc dân', 3),
('bhxh', 'bao hiem xa hoi', 'bảo hiểm xã hội', 3),
('bhyt', 'bao hiem y te', 'bảo hiểm y tế', 3),
('atgt', 'an toan giao thong', 'an toàn giao thông', 3),
('clb', 'cau lac bo', 'câu lạc bộ', 4),
('ctv', 'cong tac vien', 'cộng tác viên', 4),
('hsg', 'hoc sinh gioi', 'học sinh giỏi', 4),

-- TEENCODE BỔ SUNG - TỪ HAY BỊ THIẾU
('xog', 'xong', 'xong', 6),
('xg', 'xong', 'xong', 6),
('thoii', 'thoi', 'thôi', 6),
('ngoonn', 'ngon', 'ngon', 5),
('dii', 'di', 'đi', 6),
('dau', 'dau', 'đâu', 5),
('bn', 'bao nhieu', 'bao nhiêu', 4),
('dt', 'dien thoai', 'điện thoại', 6),
('kbt', 'khong biet', 'không biết', 5),
('klm', 'khong lam', 'không làm', 4),
('kdc', 'khong duoc', 'không được', 5),
('kdi', 'khong di', 'không đi', 4),
('mng', 'moi nguoi', 'mọi người', 5),
('nc', 'noi chuyen', 'nói chuyện', 7),
('vcl', 'vai', 'vãi', 3),
('vl', 'vai', 'vãi', 3),
('ck', 'chong', 'chồng', 6),
('sg', 'sai gon', 'sài gòn', 5),
('nt', 'nhan tin', 'nhắn tin', 7),
('ib', 'inbox', 'inbox', 6),
('ny', 'nguoi yeu', 'người yêu', 7);


-- ============================================================
-- 3. BIGRAMS (~600+ cặp từ)
-- ============================================================

INSERT INTO `bigrams` (`word1`, `word2`, `frequency`) VALUES
-- CẶP TỪ TÌNH CẢM
('anh', 'yeu', 95), ('yeu', 'em', 95), ('anh', 'nho', 85),
('nho', 'em', 85), ('anh', 'thuong', 80), ('thuong', 'em', 75),
('em', 'yeu', 90), ('toi', 'yeu', 80),
('yeu', 'ban', 75), ('thuong', 'ban', 70),
('yeu', 'anh', 85), ('nho', 'anh', 75),
('rat', 'yeu', 80), ('rat', 'thuong', 75),
('rat', 'nho', 70), ('rat', 'thich', 75),
('thich', 'ban', 70), ('thich', 'em', 70),
('ghet', 'ban', 55), ('ghet', 'no', 55),
('anh', 'oi', 80), ('em', 'oi', 80),
('ban', 'oi', 75), ('oi', 'ban', 70),
('yeu', 'thuong', 70), ('yeu', 'nhau', 65),
('nho', 'nhau', 60), ('thuong', 'nhau', 60),

-- CẶP TỪ PHỦ ĐỊNH
('khong', 'biet', 95), ('khong', 'co', 95), ('khong', 'duoc', 90),
('khong', 'the', 85), ('khong', 'muon', 85), ('khong', 'can', 80),
('khong', 'phai', 80), ('khong', 'thich', 75),
('khong', 'hieu', 75), ('khong', 'nghe', 70),
('khong', 'nho', 70), ('khong', 'thay', 70),
('khong', 'noi', 65), ('khong', 'lam', 70),
('khong', 'di', 70), ('khong', 'an', 65),
('khong', 'sao', 70), ('khong', 'dau', 65),
('khong', 'dam', 55), ('khong', 'nen', 60),
('khong', 'bao gio', 55),
('chua', 'biet', 80), ('chua', 'co', 75),
('chua', 'lam', 70), ('chua', 'an', 65),
('chua', 'di', 65), ('chua', 'xong', 65),
('chua', 'duoc', 60), ('chua', 'hieu', 55),
('dung', 'khong', 75), ('phai', 'khong', 80),

-- CẶP TỪ CHÀO HỎI
('xin', 'chao', 85), ('cam', 'on', 85), ('xin', 'loi', 80),
('tam', 'biet', 70), ('hen', 'gap', 65),
('chao', 'ban', 70), ('chao', 'anh', 65),
('chao', 'chi', 65), ('chao', 'em', 65),
('chuc', 'mung', 65), ('chuc', 'ngu', 60),
('chuc', 'vui', 60), ('rat', 'vui', 70),
('hen', 'gap', 60), ('gap', 'lai', 55),
('hen', 'gap', 55), ('gap', 'ban', 50),

-- CẶP TỪ ĐỜI THƯỜNG
('di', 'hoc', 85), ('di', 'lam', 80), ('di', 'choi', 80),
('di', 'an', 75), ('di', 'ngu', 70), ('di', 've', 75),
('di', 'ra', 65), ('di', 'vao', 65), ('di', 'len', 60),
('di', 'xuong', 55), ('di', 'dau', 75),
('di', 'mua', 60), ('di', 'xem', 60), ('di', 'gap', 55),
('ve', 'nha', 85), ('ra', 'ngoai', 65),
('an', 'com', 80), ('an', 'sang', 65), ('an', 'trua', 60),
('an', 'toi', 60), ('an', 'gi', 75),
('an', 'pho', 55), ('an', 'banh', 50),
('uong', 'nuoc', 75), ('uong', 'tra', 55), ('uong', 'bia', 45),
('doc', 'sach', 70), ('doc', 'bao', 55),
('viet', 'bai', 70), ('lam', 'bai', 75),
('lam', 'viec', 80), ('lam', 'gi', 75),
('noi', 'chuyen', 75), ('nhan', 'tin', 70),
('goi', 'dien', 65), ('gui', 'tin', 55),
('hoc', 'bai', 70), ('on', 'bai', 55),
('thi', 'dau', 50), ('thi', 'rot', 45),

-- CẶP TỪ MÔ TẢ
('rat', 'dep', 85), ('rat', 'tot', 85), ('rat', 'vui', 80),
('rat', 'buon', 75), ('rat', 'nhanh', 75), ('rat', 'nhieu', 80),
('rat', 'it', 65), ('rat', 'kho', 70), ('rat', 'de', 70),
('rat', 'ngon', 70), ('rat', 'hay', 75),
('rat', 'gioi', 65), ('rat', 'khoe', 65),
('rat', 'met', 60), ('rat', 'manh', 55),
('qua', 'dep', 75), ('qua', 'tot', 75), ('qua', 'hay', 70),
('qua', 'ngon', 65), ('qua', 'gioi', 60),
('qua', 'nhieu', 60), ('qua', 'kho', 55),
('cuc', 'dep', 60), ('cuc', 'ky', 55),
('vo', 'cung', 55), ('het', 'suc', 50),
('tuyet', 'voi', 65), ('binh', 'thuong', 65),
('don', 'gian', 55), ('phuc', 'tap', 50),

-- CẶP TỪ VỚI "LA" (là)
('toi', 'la', 80), ('day', 'la', 80), ('no', 'la', 75),
('do', 'la', 70), ('nay', 'la', 65),
('la', 'gi', 75), ('la', 'ai', 65),
('la', 'nguoi', 60), ('la', 'cai', 60),
('anh', 'la', 70), ('em', 'la', 75),
('ban', 'la', 70),

-- CẶP TỪ NGHI VẤN
('co', 'the', 80), ('nhu', 'vay', 70),
('the', 'nao', 70), ('tai', 'sao', 70),
('bao', 'gio', 65), ('luc', 'nao', 60),
('o', 'dau', 70), ('cai', 'gi', 75),
('lam', 'gi', 70), ('noi', 'gi', 70),
('la', 'sao', 65), ('vi', 'sao', 60),
('bao', 'nhieu', 60), ('may', 'gio', 55),
('lam', 'sao', 65), ('bang', 'cach', 50),
('nhu', 'the', 60), ('nhu', 'nao', 55),

-- CẶP TỪ GHÉP PHỔ BIẾN
('hanh', 'phuc', 75), ('gia', 'dinh', 80),
('cong', 'viec', 75), ('cuoc', 'song', 75),
('ban', 'be', 70), ('nguoi', 'yeu', 75),
('truong', 'hoc', 65), ('benh', 'vien', 60),
('nha', 'hang', 60), ('sieu', 'thi', 60),
('thanh', 'pho', 65), ('nong', 'thon', 50),
('dong', 'nghiep', 55), ('ban', 'hoc', 60),
('ban', 'than', 65), ('tinh', 'yeu', 70),
('su', 'that', 55), ('y', 'kien', 55),
('the', 'gioi', 60), ('xa', 'hoi', 55),
('van', 'hoa', 50), ('lich', 'su', 50),
('khoa', 'hoc', 55), ('cong', 'nghe', 60),
('suc', 'khoe', 60), ('lo', 'lang', 55),
('met', 'moi', 55), ('hoi', 'hop', 50),
('bat', 'ngo', 55), ('ngac', 'nhien', 50),
('that', 'vong', 50), ('hai', 'long', 55),
('tu', 'hao', 50), ('tu', 'tin', 55),
('dai', 'hoc', 65), ('tieu', 'hoc', 50),
('trung', 'hoc', 50), ('cao', 'dang', 45),
('kinh', 'te', 50), ('giao', 'duc', 50),
('y', 'te', 45), ('an', 'ninh', 45),
('phat', 'trien', 50), ('doi', 'moi', 45),
('sang', 'tao', 50),

-- CẶP TỪ TEENCODE THƯỜNG ĐI CÙNG
('nhanh', 'len', 65), ('di', 'di', 55),
('thoi', 'di', 60), ('duoc', 'roi', 65),
('xong', 'roi', 60), ('biet', 'roi', 60),
('hieu', 'roi', 55), ('roi', 'ha', 50),
('chua', 'vay', 55), ('duoc', 'chua', 60),
('co', 'khong', 80), ('duoc', 'khong', 75),
('tot', 'khong', 60), ('dep', 'khong', 55),
('thich', 'khong', 60), ('muon', 'khong', 60),
('biet', 'khong', 65), ('hieu', 'khong', 55),
('lam', 'roi', 55), ('di', 'roi', 55),
('an', 'roi', 50), ('ngu', 'roi', 50),

-- BIGRAMS BỔ SUNG - NGỮ CẢNH
('em', 'nho', 75), ('em', 'yeu', 80),
('em', 'biet', 70), ('em', 'muon', 65),
('em', 'co', 70), ('em', 'la', 75),
('anh', 'em', 60), ('chi', 'em', 55),
('anh', 'la', 70), ('em', 'da', 65),
('ban', 'co', 70), ('ban', 'da', 65),
('ban', 'muon', 65), ('ban', 'biet', 65),
('ban', 'la', 70), ('toi', 'da', 75),
('toi', 'muon', 80), ('toi', 'biet', 75),
('toi', 'co', 75), ('toi', 'khong', 80),
('minh', 'di', 70), ('minh', 'lam', 65),
('minh', 'an', 60), ('chung', 'ta', 65),
('chung', 'minh', 60), ('cac', 'ban', 65),

-- Context cho "y" (yêu vs ý)
('anh', 'y', 90), ('y', 'em', 90),
('t', 'y', 70), ('y', 'bn', 65),

-- CẶP TỪ CÔNG NGHỆ
('dien', 'thoai', 65), ('may', 'tinh', 60),
('mang', 'xa hoi', 50), ('ung', 'dung', 50),
('phan', 'mem', 50), ('tai', 'khoan', 50),
('mat', 'khau', 45), ('dang', 'nhap', 45),
('cap', 'nhat', 50), ('chia', 'se', 55),
('binh', 'luan', 50), ('tin', 'nhan', 50),

-- CẶP TỪ Y TẾ
('bac', 'si', 55), ('benh', 'vien', 60),
('suc', 'khoe', 60), ('chua', 'benh', 50),
('kham', 'benh', 50), ('uong', 'thuoc', 50),

-- CẶP TỪ GIAO THÔNG
('xe', 'may', 55), ('o', 'to', 50),
('xe', 'dap', 45), ('may', 'bay', 55),
('xe', 'buyt', 45), ('ket', 'xe', 45),
('giao', 'thong', 50), ('tai', 'nan', 45),

-- CẶP TỪ THỜI TIẾT
('troi', 'dep', 60), ('troi', 'mua', 55),
('troi', 'nang', 55), ('troi', 'lanh', 50),
('troi', 'nong', 50), ('thoi', 'tiet', 55),

-- CẶP TỪ GIÁO DỤC
('hoc', 'sinh', 65), ('sinh', 'vien', 65),
('giao', 'vien', 60), ('bai', 'tap', 60),
('bai', 'hoc', 55), ('mon', 'hoc', 50),
('ket', 'qua', 60), ('diem', 'so', 45),
('hoc', 'tap', 55), ('on', 'thi', 50),

-- CẶP TỪ CẢM XÚC
('vui', 've', 65), ('buon', 'ba', 50),
('lo', 'lang', 55), ('met', 'moi', 55),
('hanh', 'phuc', 70), ('that', 'vong', 50),
('chan', 'nan', 45), ('hoi', 'hop', 50),
('bat', 'ngo', 55), ('ngac', 'nhien', 50),
('tu', 'hao', 50), ('tu', 'tin', 55),
('xau', 'ho', 45), ('cam', 'dong', 50),

-- CẶP TỪ HÀNH ĐỘNG
('giup', 'do', 55), ('hop', 'tac', 50),
('an', 'uong', 65), ('o', 'nha', 65),
('o', 'truong', 55), ('bat', 'dau', 65),
('ket', 'thuc', 60), ('tiep', 'tuc', 60),
('quyet', 'dinh', 55), ('lua', 'chon', 50),
('so', 'sanh', 50), ('phan', 'tich', 45),
('danh', 'gia', 50), ('nhan', 'xet', 45),
('don', 'dep', 50), ('cham', 'soc', 55),
('nau', 'an', 60), ('giat', 'do', 45);


-- ============================================================
-- 4. REDUPLICATIVE_WORDS (~200+ từ láy)
-- ============================================================

INSERT INTO `reduplicative_words` (`word_no_accent`, `word_with_accent`, `type`, `frequency`) VALUES
-- TỪ LÁY TOÀN PHẦN
('xinh xinh', 'xinh xinh', 'full', 70),
('dep dep', 'đẹp đẹp', 'full', 60),
('nho nho', 'nhỏ nhỏ', 'full', 60),
('vui vui', 'vui vui', 'full', 60),
('buon buon', 'buồn buồn', 'full', 55),
('ngon ngon', 'ngon ngon', 'full', 55),
('nhanh nhanh', 'nhanh nhanh', 'full', 55),
('cham cham', 'chậm chậm', 'full', 50),
('tot tot', 'tốt tốt', 'full', 50),
('xau xau', 'xấu xấu', 'full', 45),
('nong nong', 'nóng nóng', 'full', 50),
('lanh lanh', 'lạnh lạnh', 'full', 50),
('ngay ngay', 'ngày ngày', 'full', 55),
('dem dem', 'đêm đêm', 'full', 50),
('it it', 'ít ít', 'full', 45),
('nhieu nhieu', 'nhiều nhiều', 'full', 45),
('cao cao', 'cao cao', 'full', 40),
('thap thap', 'thấp thấp', 'full', 40),
('dai dai', 'dài dài', 'full', 40),
('ngan ngan', 'ngắn ngắn', 'full', 40),
('sang sang', 'sáng sáng', 'full', 45),
('toi toi', 'tối tối', 'full', 40),
('do do', 'đỏ đỏ', 'full', 40),
('xanh xanh', 'xanh xanh', 'full', 45),
('vang vang', 'vàng vàng', 'full', 40),
('trang trang', 'trắng trắng', 'full', 40),

-- TỪ LÁY ÂM ĐẦU
('lung linh', 'lung linh', 'initial', 70),
('lap lanh', 'lấp lánh', 'initial', 65),
('long lanh', 'long lanh', 'initial', 60),
('lo lang', 'lo lắng', 'initial', 65),
('xinh xan', 'xinh xắn', 'initial', 65),
('xon xao', 'xôn xao', 'initial', 55),
('xao xuyen', 'xao xuyến', 'initial', 55),
('nho nhan', 'nhỏ nhắn', 'initial', 60),
('nho nhoi', 'nhỏ nhoi', 'initial', 50),
('nhe nhang', 'nhẹ nhàng', 'initial', 65),
('nhanh nhen', 'nhanh nhẹn', 'initial', 60),
('dep de', 'đẹp đẽ', 'initial', 55),
('dep doi', 'đẹp đôi', 'initial', 50),
('do dam', 'đỏ đậm', 'initial', 45),
('dam da', 'đậm đà', 'initial', 55),
('dan dan', 'dần dần', 'initial', 50),
('don dap', 'dồn dập', 'initial', 50),
('vui ve', 'vui vẻ', 'initial', 70),
('vat va', 'vất vả', 'initial', 60),
('vung ve', 'vụng về', 'initial', 50),
('bon chon', 'bồn chồn', 'initial', 55),
('be bong', 'bé bỏng', 'initial', 55),
('boi roi', 'bối rối', 'initial', 55),
('chan chu', 'chần chừ', 'initial', 55),
('chat choi', 'chật chội', 'initial', 50),
('cham chi', 'chăm chỉ', 'initial', 65),
('chan nan', 'chán nản', 'initial', 55),
('tham thiet', 'thắm thiết', 'initial', 50),
('than thiet', 'thân thiết', 'initial', 60),
('tham thuong', 'thảm thương', 'initial', 45),
('thu vi', 'thú vị', 'initial', 65),
('thong tha', 'thong thả', 'initial', 50),
('manh me', 'mạnh mẽ', 'initial', 60),
('me man', 'mê mẩn', 'initial', 50),
('ngu ngoc', 'ngu ngốc', 'initial', 55),
('thong minh', 'thông minh', 'initial', 60),
('lanh loi', 'lanh lợi', 'initial', 50),
('ruc ro', 'rực rỡ', 'initial', 60),
('nao nhiet', 'náo nhiệt', 'initial', 55),
('ngoan ngoan', 'ngoan ngoãn', 'initial', 50),
('sang sua', 'sáng sủa', 'initial', 55),
('sach se', 'sạch sẽ', 'initial', 60),
('mat me', 'mát mẻ', 'initial', 50),
('nho nhoi', 'nhỏ nhoi', 'initial', 45),
('long lay', 'lộng lẫy', 'initial', 55),
('le loi', 'lẻ loi', 'initial', 45),
('bao boc', 'bao bọc', 'initial', 50),
('benh vuc', 'bênh vực', 'initial', 45),
('chung chac', 'chững chạc', 'initial', 45),
('gon gang', 'gọn gàng', 'initial', 60),
('gioi giang', 'giỏi giang', 'initial', 50),
('hao hung', 'hào hứng', 'initial', 55),
('hap dan', 'hấp dẫn', 'initial', 60),
('kheo leo', 'khéo léo', 'initial', 55),
('khoe khoang', 'khoe khoang', 'initial', 45),
('lanh lẽo', 'lạnh lẽo', 'initial', 50),
('lo dang', 'lơ đãng', 'initial', 50),
('may man', 'may mắn', 'initial', 60),
('ngai ngung', 'ngại ngùng', 'initial', 55),
('ngap ngung', 'ngập ngừng', 'initial', 50),
('ngo ngan', 'ngỡ ngàng', 'initial', 55),
('ngo ngac', 'ngơ ngác', 'initial', 55),
('oi buc', 'oi bức', 'initial', 45),
('on ao', 'ồn ào', 'initial', 55),
('than tho', 'thẫn thờ', 'initial', 45),
('thanh thoat', 'thanh thoát', 'initial', 50),
('thu thach', 'thử thách', 'initial', 55),
('tich cuc', 'tích cực', 'initial', 55),
('tron tria', 'tròn trĩa', 'initial', 45),
('trong trai', 'trong trải', 'initial', 45),
('tuoi tan', 'tươi tắn', 'initial', 55),
('tuoi cuoi', 'tươi cười', 'initial', 55),
('vang ve', 'vắng vẻ', 'initial', 50),
('vinh quang', 'vinh quang', 'initial', 50),
('xuc dong', 'xúc động', 'initial', 55),

-- TỪ LÁY VẦN
('lao xao', 'lao xao', 'rhyme', 55),
('lao dao', 'lao đao', 'rhyme', 50),
('lon xon', 'lộn xộn', 'rhyme', 60),
('lon nhon', 'lộn nhộn', 'rhyme', 50),
('choi loi', 'chói lọi', 'rhyme', 50),
('hap tap', 'hấp tấp', 'rhyme', 50),
('lat dat', 'lật đật', 'rhyme', 50),
('lam nham', 'lẩm nhẩm', 'rhyme', 45),
('lam ram', 'lầm rầm', 'rhyme', 45),
('lang man', 'lãng mạn', 'rhyme', 60),
('khuc khich', 'khúc khích', 'rhyme', 50),
('thi tham', 'thì thầm', 'rhyme', 55),
('lo mo', 'lờ mờ', 'rhyme', 50),
('lo do', 'lờ đờ', 'rhyme', 45),
('diu dang', 'dịu dàng', 'rhyme', 60),
('ngo ngan', 'ngỡ ngàng', 'rhyme', 55),
('e de', 'e dè', 'rhyme', 45),
('tat bat', 'tất bật', 'rhyme', 55),
('yen tinh', 'yên tĩnh', 'rhyme', 60),
('yen ang', 'yên ắng', 'rhyme', 55),
('im lang', 'im lặng', 'rhyme', 65),
('song dong', 'sống động', 'rhyme', 50),
('sinh dong', 'sinh động', 'rhyme', 50),
('trang le', 'tráng lệ', 'rhyme', 50),
('huy hoang', 'huy hoàng', 'rhyme', 50),
('yeu duoi', 'yếu đuối', 'rhyme', 50),
('say dam', 'say đắm', 'rhyme', 50),
('hien lanh', 'hiền lành', 'rhyme', 55),
('mat me', 'mải mê', 'rhyme', 55),
('ham ho', 'hăm hở', 'rhyme', 45),
('chap chung', 'chập chùng', 'rhyme', 40),
('lup xup', 'lụp xụp', 'rhyme', 35),
('chan chat', 'chân chất', 'rhyme', 50),
('ngop ngop', 'ngộp ngộp', 'rhyme', 35),
('nuc no', 'nức nở', 'rhyme', 50),
('ram ro', 'rầm rộ', 'rhyme', 50),
('roi ren', 'rối ren', 'rhyme', 45),
('roi ram', 'rối rắm', 'rhyme', 40),
('tran lan', 'tràn lan', 'rhyme', 45),
('tham thia', 'thấm thía', 'rhyme', 50);


-- ============================================================
-- 5. TRIGRAMS (BỘ BA TỪ) - MỚI
-- ============================================================

INSERT INTO `trigrams` (`word1`, `word2`, `word3`, `frequency`) VALUES
-- Cụm phủ định
('khong', 'biet', 'duoc', 80),
('khong', 'the', 'nao', 75),
('khong', 'co', 'gi', 70),
('khong', 'sao', 'dau', 65),
('khong', 'co', 'ai', 60),
('khong', 'bao', 'gio', 65),
('chua', 'bao', 'gio', 60),
('khong', 'lam', 'duoc', 60),
('khong', 'muon', 'di', 55),
('khong', 'phai', 'la', 65),

-- Cụm tình cảm
('anh', 'yeu', 'em', 95),
('em', 'yeu', 'anh', 90),
('toi', 'yeu', 'ban', 75),
('rat', 'yeu', 'em', 80),
('anh', 'nho', 'em', 80),
('em', 'nho', 'anh', 75),
('rat', 'thuong', 'em', 70),
('rat', 'thich', 'ban', 65),

-- Cụm chào hỏi
('xin', 'chao', 'ban', 70),
('cam', 'on', 'ban', 70),
('xin', 'loi', 'ban', 65),
('chuc', 'ngu', 'ngon', 60),
('chuc', 'mot', 'ngay', 55),
('hen', 'gap', 'lai', 55),
('rat', 'vui', 'duoc', 55),

-- Cụm đời thường
('di', 'hoc', 'bai', 60),
('di', 'an', 'com', 65),
('di', 'lam', 'viec', 60),
('di', 'choi', 'voi', 55),
('ve', 'nha', 'di', 60),
('an', 'com', 'chua', 55),
('an', 'gi', 'chua', 50),
('uong', 'nuoc', 'di', 50),
('di', 'ngu', 'di', 50),
('lam', 'gi', 'vay', 55),

-- Cụm nghi vấn
('nhu', 'the', 'nao', 70),
('tai', 'sao', 'lai', 60),
('bao', 'gio', 'di', 55),
('o', 'dau', 'vay', 55),
('lam', 'sao', 'de', 55),
('la', 'gi', 'vay', 55),
('co', 'khong', 'vay', 55),
('duoc', 'khong', 'vay', 50),

-- Cụm mô tả
('rat', 'dep', 'trai', 55),
('rat', 'xinh', 'gai', 50),
('rat', 'tot', 'bung', 55),
('rat', 'vui', 've', 60),
('qua', 'dep', 'luon', 50),
('cuc', 'ky', 'dep', 55),
('cuc', 'ky', 'hay', 50),
('vo', 'cung', 'dep', 50),

-- Cụm thời gian
('hom', 'nay', 'di', 55),
('ngay', 'mai', 'di', 50),
('tuan', 'sau', 'di', 45),
('bay', 'gio', 'di', 50),
('luc', 'nao', 'cung', 50),
('bao', 'gio', 'cung', 50);


-- ============================================================
-- 6. COMMON_MISSPELLINGS (LỖI CHÍNH TẢ PHỔ BIẾN)
-- ============================================================

INSERT INTO `common_misspellings` (`misspelling`, `correct_word`, `correct_accent`, `error_type`) VALUES
-- Nhầm d/đ
('di hoc', 'di hoc', 'đi học', 'phonetic'),
('di lam', 'di lam', 'đi làm', 'phonetic'),
('di choi', 'di choi', 'đi chơi', 'phonetic'),
('dung', 'dung', 'đúng', 'phonetic'),
('duoc', 'duoc', 'được', 'phonetic'),
('dep', 'dep', 'đẹp', 'phonetic'),
('den', 'den', 'đến', 'phonetic'),
('doi', 'doi', 'đợi', 'phonetic'),
('dau', 'dau', 'đâu', 'phonetic'),

-- Nhầm s/x
('xin', 'xin', 'xin', 'phonetic'),
('xem', 'xem', 'xem', 'phonetic'),
('xong', 'xong', 'xong', 'phonetic'),
('xui', 'xui', 'xui', 'phonetic'),

-- Nhầm gi/d
('gia', 'gia', 'gia', 'phonetic'),
('gian', 'gian', 'giận', 'phonetic'),
('giao', 'giao', 'giao', 'phonetic'),

-- Lỗi gõ phím gần nhau
('toi', 'toi', 'tôi', 'keyboard'),
('bam', 'ban', 'bạn', 'keyboard'),
('yeu', 'yeu', 'yêu', 'keyboard'),
('nguoi', 'nguoi', 'người', 'keyboard'),

-- Lỗi thiếu/thừa dấu
('khong', 'khong', 'không', 'typo'),
('duong', 'duong', 'đường', 'typo'),
('truong', 'truong', 'trường', 'typo'),
('phuong', 'phuong', 'phương', 'typo');



-- ################################################################
-- BỔ SUNG DỮ LIỆU MỞ RỘNG (THÊM MỚI - KHÔNG XÓA GÌ BÊN TRÊN)
-- ################################################################


-- ============================================================
-- BỔ SUNG 1: TỪ ĐƠN ÂM TIẾT BỊ THIẾU (từ test tự động tìm ra)
-- ============================================================
INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
-- Từ bị thiếu phát hiện qua test
('tai', 'tại', 65, 't'),
('trai', 'trai', 60, 't'),
('gai', 'gái', 60, 'g'),
('vong', 'vọng', 50, 'v'),
('phuc', 'phúc', 55, 'p'),
('hanh', 'hạnh', 55, 'h'),
('dinh', 'đình', 55, 'd'),
('giao', 'giáo', 55, 'g'),
('duc', 'dục', 50, 'd'),
('quoc', 'quốc', 55, 'q'),
('hang', 'hàng', 60, 'h'),
('cong', 'công', 65, 'c'),
('thong', 'thông', 60, 't'),
('phat', 'phát', 55, 'p'),
('trien', 'triển', 50, 't'),
('te', 'tế', 55, 't'),
('hoi', 'hội', 55, 'h'),
('suc', 'sức', 60, 's'),
('giai', 'giải', 55, 'g'),
('bai', 'bài', 65, 'b'),
('tap', 'tập', 60, 't'),
('dien', 'điện', 60, 'd'),
('thoai', 'thoại', 55, 't'),
('mon', 'môn', 55, 'm'),
('toan', 'toán', 55, 't'),
('van', 'văn', 55, 'v'),
('su', 'sử', 50, 's'),
('dia', 'địa', 50, 'd'),
('ly', 'lý', 50, 'l'),
('hoa', 'hóa', 50, 'h'),
('sinh', 'sinh', 60, 's'),
('phap', 'pháp', 45, 'p'),
('thanh', 'thành', 60, 't'),
('binh', 'bình', 55, 'b'),
('dao', 'dạo', 50, 'd'),
('quanh', 'quanh', 50, 'q'),
('be', 'bè', 50, 'b'),
('nan', 'nản', 45, 'n'),
('soi', 'sôi', 45, 's'),
('cang', 'càng', 60, 'c'),
('hong', 'hỏng', 50, 'h'),
('xinh', 'xinh', 70, 'x'),
('tao', 'tạo', 55, 't'),
('muon', 'muộn', 55, 'm'),
('mua', 'mua', 80, 'm'),
('vui', 'vui', 80, 'v'),
('sao', 'sao', 70, 's'),
('xong', 'xong', 70, 'x'),
('cho', 'cho', 85, 'c');

-- ============================================================
-- BỔ SUNG 2: ĐỘNG TỪ MỞ RỘNG
-- ============================================================
INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
('hat', 'hát', 55, 'h'),
('nhac', 'nhạc', 50, 'n'),
('chia', 'chia', 60, 'c'),
('xep', 'xếp', 50, 'x'),
('sap xep', 'sắp xếp', 50, 's'),
('chuan bi', 'chuẩn bị', 55, 'c'),
('to chuc', 'tổ chức', 50, 't'),
('tham gia', 'tham gia', 55, 't'),
('nop', 'nộp', 50, 'n'),
('kiem tra', 'kiểm tra', 55, 'k'),
('on tap', 'ôn tập', 50, 'o'),
('lien he', 'liên hệ', 50, 'l'),
('ket noi', 'kết nối', 50, 'k'),
('huong dan', 'hướng dẫn', 50, 'h'),
('gioi thieu', 'giới thiệu', 50, 'g'),
('moi', 'mời', 55, 'm'),
('nghi ngoi', 'nghỉ ngơi', 50, 'n'),
('du lich', 'du lịch', 55, 'd'),
('tham quan', 'tham quan', 50, 't'),
('chup anh', 'chụp ảnh', 50, 'c'),
('giam', 'giảm', 55, 'g'),
('tang', 'tăng', 55, 't'),
('giu', 'giữ', 60, 'g'),
('dat', 'đạt', 55, 'd'),
('tranh', 'tránh', 55, 't'),
('chong', 'chống', 50, 'c'),
('bao ve', 'bảo vệ', 55, 'b'),
('dua', 'đưa', 60, 'd'),
('mang', 'mang', 60, 'm'),
('nem', 'ném', 45, 'n'),
('dung', 'dùng', 75, 'd'),
('su dung', 'sử dụng', 60, 's'),
('tra', 'trả', 60, 't'),
('cam', 'cấm', 45, 'c'),
('cho phep', 'cho phép', 50, 'c'),
('yeu cau', 'yêu cầu', 55, 'y'),
('phan', 'phần', 55, 'p'),
('dich', 'dịch', 45, 'd'),
('ve', 'vẽ', 50, 'v'),
('chon', 'chọn', 55, 'c'),
('tron', 'trốn', 45, 't'),
('an', 'ẩn', 40, 'a'),
('hien', 'hiện', 55, 'h'),
('xuat', 'xuất', 50, 'x'),
('nhap', 'nhập', 50, 'n'),
('xay', 'xây', 50, 'x'),
('pha', 'pha', 45, 'p'),
('tron', 'trộn', 40, 't'),
('xao', 'xào', 45, 'x'),
('chien', 'chiên', 45, 'c'),
('nuong', 'nướng', 45, 'n'),
('luoc', 'luộc', 40, 'l'),
('hap', 'hấp', 40, 'h'),
('ran', 'rán', 40, 'r'),
('khuay', 'khuấy', 35, 'k'),
('rot', 'rót', 40, 'r'),
('do', 'đổ', 45, 'd'),
('dap', 'dập', 40, 'd'),
('cuon', 'cuốn', 50, 'c'),
('goi', 'gói', 45, 'g'),
('mo', 'mở', 60, 'm'),
('tat', 'tắt', 55, 't'),
('bam', 'bấm', 50, 'b'),
('nhan', 'nhấn', 50, 'n'),
('keo', 'kéo', 50, 'k'),
('day', 'đẩy', 50, 'd'),
('dang', 'đăng', 55, 'd'),
('tai', 'tải', 50, 't'),
('luu', 'lưu', 50, 'l'),
('xoa', 'xóa', 50, 'x'),
('sao chep', 'sao chép', 45, 's'),
('dan', 'dán', 45, 'd'),
('in', 'in', 40, 'i'),
('scan', 'scan', 35, 's'),
('go', 'gõ', 45, 'g'),
('danh', 'đánh', 60, 'd'),
('da', 'đá', 50, 'd'),
('sut', 'sút', 45, 's'),
('nem', 'ném', 45, 'n'),
('bat', 'bắt', 55, 'b'),
('than', 'thân', 55, 't'),
('the', 'thể', 55, 't');

-- ============================================================
-- BỔ SUNG 3: TÍNH TỪ MỞ RỘNG
-- ============================================================
INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
('sang trong', 'sang trọng', 50, 's'),
('giau', 'giàu', 50, 'g'),
('ngheo', 'nghèo', 50, 'n'),
('thong minh', 'thông minh', 55, 't'),
('khon', 'khôn', 45, 'k'),
('dung cam', 'dũng cảm', 45, 'd'),
('trung thuc', 'trung thực', 50, 't'),
('cham chi', 'chăm chỉ', 55, 'c'),
('luoi', 'lười', 50, 'l'),
('can than', 'cẩn thận', 55, 'c'),
('tu te', 'tử tế', 50, 't'),
('y nghia', 'ý nghĩa', 50, 'y'),
('buon cuoi', 'buồn cười', 50, 'b'),
('binh an', 'bình an', 50, 'b'),
('thanh binh', 'thanh bình', 50, 't'),
('dang yeu', 'đáng yêu', 65, 'd'),
('de thuong', 'dễ thương', 65, 'd'),
('hung', 'hứng', 45, 'h'),
('chan', 'chán', 55, 'c'),
('ngon', 'ngon', 65, 'n'),
('sau', 'sâu', 50, 's'),
('rong', 'rộng', 55, 'r'),
('trong', 'trọng', 55, 't'),
('vui tinh', 'vui tính', 50, 'v'),
('hien', 'hiền', 50, 'h'),
('du', 'dữ', 40, 'd'),
('ngoan', 'ngoan', 55, 'n'),
('hu', 'hư', 45, 'h'),
('cham', 'chăm', 50, 'c'),
('nang dong', 'năng động', 50, 'n'),
('tich cuc', 'tích cực', 50, 't'),
('tieu cuc', 'tiêu cực', 45, 't'),
('lac quan', 'lạc quan', 50, 'l'),
('bi quan', 'bi quan', 40, 'b'),
('that tha', 'thật thà', 50, 't'),
('gia doi', 'giả dối', 40, 'g'),
('kien nhan', 'kiên nhẫn', 50, 'k'),
('nong nay', 'nóng nảy', 45, 'n'),
('rong luong', 'rộng lượng', 45, 'r'),
('ky', 'kỹ', 50, 'k'),
('cau ky', 'cầu kỳ', 40, 'c'),
('xuat sac', 'xuất sắc', 55, 'x'),
('tam thuong', 'tầm thường', 40, 't'),
('phi thuong', 'phi thường', 40, 'p'),
('binh dan', 'bình dân', 45, 'b'),
('sang chanh', 'sang chảnh', 45, 's'),
('xin', 'xịn', 45, 'x');

-- ============================================================
-- BỔ SUNG 4: DANH TỪ MỞ RỘNG
-- ============================================================
INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
-- Sự kiện / Lễ hội
('su kien', 'sự kiện', 50, 's'),
('le hoi', 'lễ hội', 50, 'l'),
('tet', 'tết', 55, 't'),
('giang sinh', 'giáng sinh', 40, 'g'),
('quoc khanh', 'quốc khánh', 35, 'q'),
('nghi le', 'nghỉ lễ', 45, 'n'),
('ky nghi', 'kỳ nghỉ', 45, 'k'),
('chuyen di', 'chuyến đi', 50, 'c'),
('ve', 'vé', 45, 'v'),
('hanh ly', 'hành lý', 40, 'h'),
('khach san', 'khách sạn', 50, 'k'),
('nha nghi', 'nhà nghỉ', 45, 'n'),
-- Ẩm thực
('am thuc', 'ẩm thực', 45, 'a'),
('mon ngon', 'món ngon', 50, 'm'),
('dac san', 'đặc sản', 45, 'd'),
('nem', 'nem', 40, 'n'),
('dua', 'dưa', 45, 'd'),
('ot', 'ớt', 40, 'o'),
('hanh', 'hành', 40, 'h'),
('toi', 'tỏi', 40, 't'),
('gung', 'gừng', 35, 'g'),
('duong', 'đường', 55, 'd'),
('muoi', 'muối', 45, 'm'),
('nuoc mam', 'nước mắm', 40, 'n'),
('tuong', 'tương', 40, 't'),
('dau', 'dầu', 45, 'd'),
('bo', 'bơ', 40, 'b'),
-- Thương mại
('hang hoa', 'hàng hóa', 50, 'h'),
('san pham', 'sản phẩm', 55, 's'),
('dich vu', 'dịch vụ', 50, 'd'),
('chat luong', 'chất lượng', 55, 'c'),
('gia ca', 'giá cả', 45, 'g'),
('thuong hieu', 'thương hiệu', 40, 't'),
('khach hang', 'khách hàng', 50, 'k'),
('nhan vien', 'nhân viên', 55, 'n'),
('giam doc', 'giám đốc', 45, 'g'),
('ke toan', 'kế toán', 40, 'k'),
('ky su', 'kỹ sư', 45, 'k'),
('luat su', 'luật sư', 40, 'l'),
('ca si', 'ca sĩ', 45, 'c'),
('dien vien', 'diễn viên', 40, 'd'),
('nha van', 'nhà văn', 40, 'n'),
('nha bao', 'nhà báo', 40, 'n'),
-- Xã hội
('chinh tri', 'chính trị', 45, 'c'),
('luat', 'luật', 45, 'l'),
('quyen', 'quyền', 50, 'q'),
('trach nhiem', 'trách nhiệm', 45, 't'),
('tu do', 'tự do', 50, 't'),
('hoa binh', 'hòa bình', 50, 'h'),
-- Đồ vật mở rộng
('tu lanh', 'tủ lạnh', 45, 't'),
('may giat', 'máy giặt', 40, 'm'),
('lo vi song', 'lò vi sóng', 35, 'l'),
('quat', 'quạt', 40, 'q'),
('dieu hoa', 'điều hòa', 45, 'd'),
('bep', 'bếp', 45, 'b'),
('noi', 'nồi', 40, 'n'),
('chao', 'chảo', 40, 'c'),
('dao', 'dao', 40, 'd'),
('thot', 'thớt', 35, 't'),
('chen', 'chén', 40, 'c'),
('bat', 'bát', 45, 'b'),
('dia', 'đĩa', 40, 'd'),
('khay', 'khay', 35, 'k'),
('muong', 'muỗng', 40, 'm'),
('dua', 'đũa', 45, 'd'),
('ly', 'ly', 45, 'l'),
('coc', 'cốc', 45, 'c'),
('binh', 'bình', 40, 'b'),
('chai', 'chai', 40, 'c'),
('lon', 'lon', 35, 'l'),
('hop', 'hộp', 40, 'h'),
('tui', 'túi', 50, 't'),
('bao', 'bao', 45, 'b'),
-- Phương tiện
('xe buyt', 'xe buýt', 45, 'x'),
('tau', 'tàu', 45, 't'),
('may bay', 'máy bay', 50, 'm'),
('thuyen', 'thuyền', 40, 't'),
('xe lam', 'xe lam', 35, 'x'),
('xich lo', 'xích lô', 35, 'x'),
('xe khach', 'xe khách', 40, 'x'),
('taxi', 'taxi', 45, 't'),
('grab', 'grab', 40, 'g'),
-- Thể thao mở rộng
('bong da', 'bóng đá', 55, 'b'),
('bong ro', 'bóng rổ', 40, 'b'),
('cau long', 'cầu lông', 45, 'c'),
('boi loi', 'bơi lội', 40, 'b'),
('chay bo', 'chạy bộ', 50, 'c'),
('the duc', 'thể dục', 50, 't'),
('the thao', 'thể thao', 55, 't'),
('tran dau', 'trận đấu', 45, 't'),
('vo dich', 'vô địch', 45, 'v'),
('diem', 'điểm', 55, 'd'),
('giai', 'giải', 50, 'g'),
('cup', 'cúp', 40, 'c'),
('huy chuong', 'huy chương', 40, 'h'),
-- Nơi chốn mở rộng
('san bay', 'sân bay', 50, 's'),
('ben xe', 'bến xe', 50, 'b'),
('nha ga', 'nhà ga', 45, 'n'),
('cang', 'cảng', 40, 'c'),
('tram', 'trạm', 40, 't'),
('nha tho', 'nhà thờ', 45, 'n'),
('chua', 'chùa', 45, 'c'),
('dinh', 'đình', 40, 'd'),
('lang', 'làng', 50, 'l'),
('pho', 'phố', 55, 'p'),
('ngo', 'ngõ', 45, 'n'),
('hem', 'hẻm', 45, 'h'),
('quan', 'quận', 55, 'q'),
('phuong', 'phường', 55, 'p'),
('tinh', 'tỉnh', 55, 't'),
('huyen', 'huyện', 50, 'h'),
('thi tran', 'thị trấn', 40, 't'),
('rap', 'rạp', 45, 'r'),
('rap phim', 'rạp phim', 45, 'r'),
('rap hat', 'rạp hát', 35, 'r'),
('bao tang', 'bảo tàng', 40, 'b'),
('thu vien', 'thư viện', 45, 't');

-- ============================================================
-- BỔ SUNG 5: TRẠNG TỪ / LIÊN TỪ BỔ SUNG
-- ============================================================
INSERT INTO `vietnamese_words` (`word`, `word_with_accent`, `frequency`, `first_letter`) VALUES
('lien tuc', 'liên tục', 50, 'l'),
('thuong xuyen', 'thường xuyên', 50, 't'),
('doi khi', 'đôi khi', 55, 'd'),
('thinh thoang', 'thỉnh thoảng', 50, 't'),
('luon luon', 'luôn luôn', 55, 'l'),
('hay la', 'hay là', 55, 'h'),
('lai', 'lại', 70, 'l'),
('nua', 'nữa', 65, 'n'),
('them', 'thêm', 60, 't'),
('bot', 'bớt', 50, 'b'),
('moi', 'mỗi', 55, 'm'),
('tung', 'từng', 60, 't'),
('hang', 'hằng', 50, 'h'),
('deu', 'đều', 55, 'd'),
('hau nhu', 'hầu như', 50, 'h'),
('hau het', 'hầu hết', 50, 'h'),
('it nhat', 'ít nhất', 50, 'i'),
('nhieu nhat', 'nhiều nhất', 55, 'n'),
('chi', 'chỉ', 70, 'c'),
('rieng', 'riêng', 50, 'r'),
('chung', 'chung', 55, 'c'),
('toan', 'toàn', 50, 't'),
('toan bo', 'toàn bộ', 50, 't'),
('phan', 'phần', 55, 'p'),
('mot phan', 'một phần', 45, 'm'),
('tat ca', 'tất cả', 70, 't'),
('moi', 'mọi', 60, 'm'),
('tuy', 'tùy', 45, 't'),
('minh', 'minh', 55, 'm'),
('dat', 'đặt', 50, 'd'),
('hop', 'hợp', 50, 'h'),
('co le', 'có lẽ', 60, 'c'),
('chac', 'chắc', 55, 'c'),
('chac chan', 'chắc chắn', 55, 'c'),
('co the', 'có thể', 70, 'c'),
('nen', 'nên', 80, 'n'),
('dung', 'đừng', 65, 'd'),
('hay', 'hãy', 70, 'h'),
('cu', 'cứ', 55, 'c'),
('cung', 'cùng', 60, 'c'),
('nhau', 'nhau', 65, 'n'),
('cung nhau', 'cùng nhau', 55, 'c'),
('voi nhau', 'với nhau', 55, 'v');

-- ============================================================
-- BỔ SUNG 6: VIẾT TẮT / TEENCODE MỚI
-- ============================================================
INSERT INTO `abbreviations` (`abbreviation`, `full_word`, `full_word_accent`, `priority`) VALUES
-- Teencode đời thường
('xog', 'xong', 'xong', 6),
('xg', 'xong', 'xong', 6),
('thoii', 'thoi', 'thôi', 6),
('dii', 'di', 'đi', 6),
('mng', 'moi nguoi', 'mọi người', 5),
('ny', 'nguoi yeu', 'người yêu', 7),
('ck', 'chong', 'chồng', 6),
('vk', 'vo', 'vợ', 6),
('ib', 'inbox', 'inbox', 6),
('fb', 'facebook', 'facebook', 6),
('acc', 'tai khoan', 'tài khoản', 4),
('pass', 'mat khau', 'mật khẩu', 4),
('pic', 'hinh anh', 'hình ảnh', 4),
('vid', 'video', 'video', 4),
('cmt', 'binh luan', 'bình luận', 5),
('pls', 'xin', 'xin', 5),
('plz', 'xin', 'xin', 5),
('omg', 'troi oi', 'trời ơi', 4),
('lol', 'cuoi', 'cười', 4),
('np', 'khong co gi', 'không có gì', 4),
('ad', 'admin', 'admin', 4),
-- Gen Z mở rộng
('zui', 'vui', 'vui', 6),
('bùn', 'buon', 'buồn', 6),
('nè', 'nay', 'này', 6),
('ni', 'nay', 'này', 6),
('nge', 'nghe', 'nghe', 6),
('trg', 'truong', 'trường', 5),
('dag', 'dang', 'đang', 6),
('rr', 'roi roi', 'rồi rồi', 4),
('cmn', 'cua minh', 'của mình', 5),
('tml', 'thuong minh lam', 'thương mình lắm', 5),
('kbt', 'khong biet', 'không biết', 5),
('klm', 'khong lam', 'không làm', 4),
('kdi', 'khong di', 'không đi', 4),
-- Viết tắt nghề nghiệp
('bs', 'bac si', 'bác sĩ', 5),
('gs', 'giao su', 'giáo sư', 4),
('ts', 'tien si', 'tiến sĩ', 4),
('ths', 'thac si', 'thạc sĩ', 4),
('cn', 'cu nhan', 'cử nhân', 3),
('kt', 'ke toan', 'kế toán', 4),
-- Viết tắt địa danh
('hcm', 'ho chi minh', 'hồ chí minh', 5),
('hn', 'ha noi', 'hà nội', 5),
('dn', 'da nang', 'đà nẵng', 4),
('dl', 'da lat', 'đà lạt', 4),
('hp', 'hai phong', 'hải phòng', 4),
('hue', 'hue', 'huế', 5),
('ct', 'can tho', 'cần thơ', 4),
('vt', 'vung tau', 'vũng tàu', 4),
('sg', 'sai gon', 'sài gòn', 5),
('tp', 'thanh pho', 'thành phố', 5),
-- Internet
('sub', 'dang ky', 'đăng ký', 4),
('like', 'thich', 'thích', 5),
('share', 'chia se', 'chia sẻ', 5),
('rep', 'tra loi', 'trả lời', 6),
('ss', 'so sanh', 'so sánh', 5),
('kq', 'ket qua', 'kết quả', 5),
('tg', 'thoi gian', 'thời gian', 5),
('mt', 'may tinh', 'máy tính', 5),
('ktra', 'kiem tra', 'kiểm tra', 5),
-- Đọc/viết tắt nhanh
('qtrong', 'quan trong', 'quan trọng', 5),
('bt', 'binh thuong', 'bình thường', 5),
('ng', 'nguoi', 'người', 5),
('gt', 'gioi thieu', 'giới thiệu', 5),
('ctrinh', 'chuong trinh', 'chương trình', 4),
('hthong', 'he thong', 'hệ thống', 4),
('tke', 'thiet ke', 'thiết kế', 4),
('cntt', 'cong nghe thong tin', 'công nghệ thông tin', 5),
('clb', 'cau lac bo', 'câu lạc bộ', 4);

-- ============================================================
-- BỔ SUNG 7: BIGRAMS MỚI (cặp từ đi cùng nhau)
-- ============================================================
INSERT INTO `bigrams` (`word1`, `word2`, `frequency`) VALUES
-- Cặp từ bổ sung ngữ cảnh mở rộng
('hanh', 'phuc', 75),
('gia', 'dinh', 80),
('cong', 'viec', 75),
('cuoc', 'song', 75),
('tai', 'sao', 70),
('the', 'nao', 70),
('lam', 'sao', 65),
('suc', 'khoe', 60),
('giao', 'duc', 50),
('phat', 'trien', 50),
('cong', 'nghe', 60),
('thong', 'tin', 55),
('kinh', 'te', 50),
('xa', 'hoi', 50),
('quan', 'trong', 55),
('dien', 'thoai', 60),
('may', 'tinh', 55),
('bai', 'tap', 65),
('bai', 'hoc', 60),
('mon', 'hoc', 55),
('mon', 'an', 55),
('ket', 'qua', 60),
('van', 'de', 60),
('vuot', 'qua', 50),
('hoan', 'thanh', 55),
-- Cặp từ đời thường
('nhanh', 'len', 65),
('thoi', 'di', 60),
('duoc', 'roi', 65),
('xong', 'roi', 60),
('biet', 'roi', 60),
('di', 'ngu', 60),
('di', 'dao', 50),
('di', 'thi', 55),
('di', 'uong', 50),
('di', 'tap', 45),
('an', 'pho', 55),
('an', 'banh', 50),
('uong', 'sua', 45),
('uong', 'bia', 40),
('doc', 'bao', 50),
('doc', 'truyen', 45),
('xem', 'phim', 55),
('xem', 'tivi', 45),
('nghe', 'nhac', 55),
('hat', 'karaoke', 35),
('choi', 'game', 40),
('choi', 'bong', 45),
('tap', 'the', 40),
('tap', 'duc', 40),
-- Cặp từ tình cảm mở rộng
('nho', 'lam', 60),
('thuong', 'lam', 55),
('yeu', 'lam', 55),
('dep', 'lam', 60),
('gioi', 'lam', 55),
('hay', 'lam', 60),
('vui', 'lam', 55),
('buon', 'lam', 50),
('so', 'lam', 45),
('met', 'lam', 50),
('nhieu', 'lam', 60),
-- Cặp từ hỏi đáp
('khong', 'biet', 95),
('khong', 'hieu', 75),
('khong', 'sao', 70),
('khong', 'can', 75),
('bao', 'nhieu', 60),
('may', 'gio', 55),
('co', 'khong', 80),
('roi', 'chua', 55),
('chua', 'xong', 55),
('duoc', 'chua', 60),
('song', 'o', 50),
('lam', 'o', 45),
('hoc', 'o', 50),
('o', 'dau', 65),
-- Ngữ cảnh bổ sung
('ngay', 'hom', 50),
('hom', 'nay', 70),
('hom', 'qua', 60),
('ngay', 'mai', 65),
('tuan', 'nay', 55),
('thang', 'nay', 50),
('nam', 'nay', 55),
('cuoi', 'tuan', 55),
('sang', 'nay', 55),
('chieu', 'nay', 55),
('toi', 'nay', 55),
('dem', 'nay', 50),
('trua', 'nay', 45),
('bo', 'me', 60),
('anh', 'chi', 50),
('con', 'cai', 50),
('anh', 'trai', 55),
('chi', 'gai', 50),
('em', 'gai', 50),
('em', 'trai', 50),
-- Mô tả bổ sung
('rat', 'lon', 55),
('rat', 'nho', 45),
('rat', 'cao', 45),
('rat', 'thap', 40),
('rat', 'nhanh', 55),
('rat', 'cham', 45),
('rat', 'nong', 45),
('rat', 'lanh', 45),
('rat', 'moi', 50),
('rat', 'cu', 40),
('cuc', 'dep', 55),
('cuc', 'ngon', 50),
('cuc', 'hay', 50),
('cuc', 'tot', 50),
('sieu', 'dep', 50),
('sieu', 'ngon', 45),
('sieu', 'hay', 45);

-- ============================================================
-- BỔ SUNG 8: TỪ LÁY MỚI
-- ============================================================
INSERT INTO `reduplicative_words` (`word_no_accent`, `word_with_accent`, `type`, `frequency`) VALUES
-- Từ láy âm đầu bổ sung
('hap dan', 'hấp dẫn', 'initial', 60),
('may man', 'may mắn', 'initial', 60),
('ngai ngung', 'ngại ngùng', 'initial', 55),
('ngo ngang', 'ngỡ ngàng', 'initial', 55),
('ngo ngac', 'ngơ ngác', 'initial', 55),
('on ao', 'ồn ào', 'initial', 55),
('tuoi tan', 'tươi tắn', 'initial', 55),
('vang ve', 'vắng vẻ', 'initial', 50),
('long lay', 'lộng lẫy', 'initial', 55),
('sang sua', 'sáng sủa', 'initial', 55),
('hao hung', 'hào hứng', 'initial', 55),
('kheo leo', 'khéo léo', 'initial', 55),
('gioi giang', 'giỏi giang', 'initial', 50),
('mat me', 'mát mẻ', 'initial', 50),
('lanh leo', 'lạnh lẽo', 'initial', 50),
('bao boc', 'bao bọc', 'initial', 50),
('lang man', 'lãng mạn', 'initial', 60),
('tan tuy', 'tận tụy', 'initial', 45),
('tan tam', 'tận tâm', 'initial', 45),
('hien lanh', 'hiền lành', 'initial', 55),
-- Từ láy vần bổ sung
('lat dat', 'lật đật', 'rhyme', 50),
('thi tham', 'thì thầm', 'rhyme', 55),
('lo mo', 'lờ mờ', 'rhyme', 50),
('diu dang', 'dịu dàng', 'rhyme', 60),
('tat bat', 'tất bật', 'rhyme', 55),
('yen tinh', 'yên tĩnh', 'rhyme', 60),
('yen ang', 'yên ắng', 'rhyme', 55),
('song dong', 'sống động', 'rhyme', 50),
('sinh dong', 'sinh động', 'rhyme', 50),
('huy hoang', 'huy hoàng', 'rhyme', 50),
('say dam', 'say đắm', 'rhyme', 50),
('nuc no', 'nức nở', 'rhyme', 50),
('thanh binh', 'thanh bình', 'rhyme', 55),
('nong nan', 'nồng nàn', 'rhyme', 55),
('chan chat', 'chân chất', 'rhyme', 50),
-- Từ láy toàn phần bổ sung
('doi doi', 'đời đời', 'full', 40),
('noi noi', 'nơi nơi', 'full', 40),
('nguoi nguoi', 'người người', 'full', 40),
('nha nha', 'nhà nhà', 'full', 40),
('tung tung', 'từng từng', 'full', 35),
('ngay ngay', 'ngày ngày', 'full', 55),
('dem dem', 'đêm đêm', 'full', 50),
('cao cao', 'cao cao', 'full', 40),
('xanh xanh', 'xanh xanh', 'full', 45),
('do do', 'đỏ đỏ', 'full', 40),
('vang vang', 'vàng vàng', 'full', 40),
('trang trang', 'trắng trắng', 'full', 40),
('sang sang', 'sáng sáng', 'full', 45),
-- Từ ghép mở rộng
('de dang', 'dễ dàng', 'initial', 55),
('kho khan', 'khó khăn', 'initial', 55),
('phu hop', 'phù hợp', 'initial', 50),
('doc dao', 'độc đáo', 'initial', 50),
('noi bat', 'nổi bật', 'initial', 55),
('an tuong', 'ấn tượng', 'initial', 55),
('thuong thuc', 'thưởng thức', 'initial', 50),
('tran trong', 'trân trọng', 'initial', 50),
('coi mo', 'cởi mở', 'initial', 50),
('chan thanh', 'chân thành', 'initial', 55),
('lich su', 'lịch sự', 'initial', 55);

-- ============================================================
-- BỔ SUNG 9: TRIGRAMS MỚI (bộ 3 từ ngữ cảnh)
-- ============================================================
INSERT INTO `trigrams` (`word1`, `word2`, `word3`, `frequency`) VALUES
-- Ngữ cảnh thường gặp
('toi', 'muon', 'di', 60),
('toi', 'muon', 'an', 55),
('toi', 'dang', 'lam', 55),
('toi', 'da', 'lam', 55),
('toi', 'se', 'di', 50),
('em', 'dang', 'lam', 50),
('em', 'da', 'lam', 50),
('anh', 'dang', 'o', 50),
('ban', 'co', 'khoe', 55),
('ban', 'da', 'an', 50),
('ban', 'muon', 'an', 50),
('may', 'gio', 'roi', 50),
('di', 'du', 'lich', 45),
('mon', 'an', 'ngon', 45),
('bai', 'tap', 've', 50),
('tap', 've', 'nha', 50),
('cong', 'nghe', 'thong', 50),
('nghe', 'thong', 'tin', 50),
('giao', 'duc', 'la', 45),
('kinh', 'te', 'xa', 45),
('te', 'xa', 'hoi', 45),
('suc', 'khoe', 'la', 50),
('khoe', 'la', 'quan', 45),
('la', 'quan', 'trong', 50),
('quan', 'trong', 'nhat', 50),
('gia', 'dinh', 'toi', 55),
-- Câu cảm thán
('dep', 'qua', 'troi', 55),
('hay', 'qua', 'troi', 50),
('ngon', 'qua', 'troi', 50),
('vui', 'qua', 'troi', 50),
('buon', 'qua', 'troi', 45),
('met', 'qua', 'troi', 45),
('dep', 'qua', 'di', 50),
('hay', 'qua', 'di', 45),
-- Hỏi đáp
('ban', 'la', 'ai', 45),
('ban', 'o', 'dau', 50),
('ban', 'lam', 'gi', 50),
('ban', 'di', 'dau', 50),
('an', 'gi', 'chua', 50),
('nhu', 'the', 'nao', 70),
('co', 'khong', 'vay', 55),
('duoc', 'khong', 'vay', 50),
('cai', 'nay', 'la', 45),
('o', 'dau', 'vay', 55),
('lam', 'gi', 'vay', 55);

-- ============================================================
-- BỔ SUNG 10: LỖI CHÍNH TẢ PHỔ BIẾN MỞ RỘNG
-- ============================================================
INSERT INTO `common_misspellings` (`misspelling`, `correct_word`, `correct_accent`, `error_type`) VALUES
('trien', 'trien', 'triển', 'phonetic'),
('sach', 'sach', 'sách', 'phonetic'),
('quyet', 'quyet', 'quyết', 'phonetic'),
('tuyen', 'tuyen', 'tuyến', 'phonetic'),
('thuyet', 'thuyet', 'thuyết', 'phonetic'),
('kiem', 'kiem', 'kiểm', 'phonetic'),
('dieu', 'dieu', 'điều', 'phonetic'),
('giao', 'giao', 'giáo', 'phonetic'),
('biet', 'biet', 'biết', 'phonetic'),
('viet', 'viet', 'viết', 'phonetic'),
('hieu', 'hieu', 'hiểu', 'phonetic'),
('thieu', 'thieu', 'thiếu', 'phonetic'),
('nhieu', 'nhieu', 'nhiều', 'phonetic'),
('trieu', 'trieu', 'triệu', 'phonetic'),
('muon', 'muon', 'muốn', 'phonetic'),
('buon', 'buon', 'buồn', 'phonetic'),
('thuong', 'thuong', 'thương', 'phonetic'),
('duong', 'duong', 'đường', 'phonetic'),
('chuong', 'chuong', 'chương', 'phonetic'),
('luong', 'luong', 'lương', 'phonetic');


-- ============================================================
-- HOÀN TẤT
-- ============================================================
SELECT 'Database vietnamese_normalizer đã được tạo thành công!' AS message;
SELECT CONCAT('Tổng từ điển: ', COUNT(*)) AS info FROM vietnamese_words;
SELECT CONCAT('Tổng viết tắt: ', COUNT(*)) AS info FROM abbreviations;
SELECT CONCAT('Tổng bigrams: ', COUNT(*)) AS info FROM bigrams;
SELECT CONCAT('Tổng từ láy: ', COUNT(*)) AS info FROM reduplicative_words;
SELECT CONCAT('Tổng trigrams: ', COUNT(*)) AS info FROM trigrams;
SELECT CONCAT('Tổng lỗi chính tả: ', COUNT(*)) AS info FROM common_misspellings;
